/**
 * Converts the food library into a SQL migration for the `foods` table.
 * Per docs/build-brief.md section 5.
 *
 * Run with: npx tsx scripts/seed-foods.ts
 * Writes: supabase/migrations/<timestamp>_seed_foods_batch_1.sql
 *
 * Diet tiers (strictest to least strict): vegan < vegetarian < eggetarian
 * < pescatarian < non_vegetarian. Each dish is tagged with the loosest
 * tier still required to eat it. No beef anywhere in this library --
 * where the original prototype recipe used beef, it's substituted here
 * (see "Chicken burger", ex-"Cheeseburger"; "Spaghetti bolognese" now
 * specifies chicken or mutton mince rather than unspecified "minced meat").
 *
 * meal_category: which meal(s) this dish suits -- detox, breakfast,
 * lunch, snack, dinner, salad. A dish can suit more than one.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

type Diet = "vegan" | "vegetarian" | "eggetarian" | "pescatarian" | "non_vegetarian";
type Meal = "detox" | "breakfast" | "lunch" | "snack" | "dinner" | "salad";

interface Dish {
  name: string;
  cuisine: string;
  diet: Diet;
  meals: Meal[];
  serving: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  ingredients: string;
  method: string;
}

// Batch 1: the original prototype library (reference/prototype.html's RAW
// array), reclassified with diet tier and meal category. Values are
// estimates per typical home serving.
const BATCH_1: Dish[] = [
  { name: "Roti / phulka", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 medium (40 g)", kcal: 100, protein: 3, carbs: 20, fat: 1, ingredients: "Whole wheat flour, water, salt", method: "Knead a soft dough, rest 15 minutes, roll thin and cook on a hot tawa until it puffs. Skip the ghee to keep it light." },
  { name: "Plain paratha", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "lunch", "dinner"], serving: "1 (80 g)", kcal: 200, protein: 5, carbs: 30, fat: 7, ingredients: "Wheat flour, water, oil or ghee, salt", method: "Knead, roll, fold into layers and cook on a tawa with a little oil until golden on both sides." },
  { name: "Aloo paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 (120 g)", kcal: 290, protein: 6, carbs: 40, fat: 12, ingredients: "Wheat flour, boiled potato, green chilli, coriander, cumin, salt, oil", method: "Mix mashed potato with spices, stuff into dough, roll gently and cook with a little oil until crisp and golden." },
  { name: "Steamed rice", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 cup cooked (150 g)", kcal: 195, protein: 4, carbs: 43, fat: 0, ingredients: "Rice, water", method: "Rinse the rice, simmer with about twice the water until fluffy, then rest covered for 5 minutes." },
  { name: "Jeera rice", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 cup (150 g)", kcal: 240, protein: 4, carbs: 44, fat: 5, ingredients: "Basmati rice, cumin seeds, ghee, salt", method: "Sizzle cumin in ghee, add rinsed rice and water, and cook until each grain is separate." },
  { name: "Dal tadka", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 180, protein: 9, carbs: 24, fat: 5, ingredients: "Toor or moong dal, turmeric, tomato, garlic, cumin, chilli, ghee", method: "Pressure-cook the dal with turmeric, mash lightly, then pour over a tempering of ghee, cumin, garlic and chilli." },
  { name: "Moong dal khichdi", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 g)", kcal: 260, protein: 10, carbs: 44, fat: 5, ingredients: "Rice, split moong dal, turmeric, ginger, cumin, ghee, salt", method: "Pressure-cook rice and dal with turmeric and salt until soft, then finish with a ghee and cumin tempering." },
  { name: "Rajma masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 210, protein: 10, carbs: 30, fat: 6, ingredients: "Kidney beans, onion, tomato, ginger-garlic, rajma masala, oil", method: "Soak beans overnight and pressure-cook. Simmer in an onion-tomato masala for 15 minutes until thick." },
  { name: "Chana masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 240, protein: 10, carbs: 32, fat: 8, ingredients: "Chickpeas, onion, tomato, ginger-garlic, chana masala, oil", method: "Cook boiled chickpeas in a browned onion-tomato masala for 15 minutes and finish with lemon and coriander." },
  { name: "Palak paneer", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 260, protein: 12, carbs: 9, fat: 19, ingredients: "Spinach, paneer, onion, tomato, garlic, cumin, cream, oil", method: "Blanch and blend the spinach, cook it with a garlic-tomato masala, then fold in paneer cubes." },
  { name: "Paneer butter masala", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 380, protein: 14, carbs: 12, fat: 30, ingredients: "Paneer, tomato, cashew, butter, cream, kasuri methi, spices", method: "Simmer blended tomato and cashew with spices and butter, then add paneer, cream and crushed kasuri methi." },
  { name: "Butter chicken", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 360, protein: 25, carbs: 9, fat: 24, ingredients: "Chicken, yogurt, tomato puree, butter, cream, garam masala, kasuri methi", method: "Marinate and grill the chicken, simmer it in buttery tomato gravy and finish with a splash of cream." },
  { name: "Chicken curry (home style)", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 280, protein: 26, carbs: 7, fat: 16, ingredients: "Chicken, onion, tomato, ginger-garlic, turmeric, coriander powder, garam masala, oil", method: "Brown the onions, add spices and tomato, then cook the chicken covered until tender, about 25 minutes." },
  { name: "Egg curry", cuisine: "Indian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "2 eggs with gravy", kcal: 260, protein: 15, carbs: 8, fat: 18, ingredients: "Boiled eggs, onion, tomato, ginger-garlic, spices, oil", method: "Make an onion-tomato masala, simmer with water for 8 minutes, add halved boiled eggs and cook 5 minutes more." },
  { name: "Aloo gobi", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 150, protein: 4, carbs: 18, fat: 7, ingredients: "Potato, cauliflower, cumin, turmeric, tomato, coriander, oil", method: "Sauté cumin and spices, add potato and cauliflower, cover and cook on low heat until tender." },
  { name: "Bhindi masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (130 g)", kcal: 120, protein: 3, carbs: 10, fat: 8, ingredients: "Okra, onion, tomato, amchur, cumin, turmeric, oil", method: "Cook dry okra on high heat so it stays crisp, then toss with onion, spices and amchur." },
  { name: "Baingan bharta", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 140, protein: 3, carbs: 12, fat: 9, ingredients: "Roasted aubergine, onion, tomato, garlic, green chilli, oil", method: "Roast the aubergine over a flame, peel and mash, then cook with sautéed onion, tomato and spices." },
  { name: "Idli", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 pieces (100 g)", kcal: 130, protein: 4, carbs: 27, fat: 1, ingredients: "Idli rice, urad dal, salt", method: "Ferment the ground rice and dal batter overnight, pour into moulds and steam for 10 to 12 minutes." },
  { name: "Plain dosa", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 medium", kcal: 150, protein: 3, carbs: 25, fat: 4, ingredients: "Rice, urad dal, fenugreek, salt, a little oil", method: "Spread fermented batter thin on a hot tawa, drizzle a little oil and cook until crisp and golden." },
  { name: "Masala dosa", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 with potato filling", kcal: 340, protein: 7, carbs: 48, fat: 13, ingredients: "Dosa batter, potato, onion, mustard seeds, curry leaves, turmeric, oil", method: "Make a soft potato masala with mustard and onion, then roll it inside a crisp dosa." },
  { name: "Sambar", cuisine: "Indian", diet: "vegan", meals: ["breakfast", "lunch"], serving: "1 katori (150 g)", kcal: 90, protein: 4, carbs: 13, fat: 3, ingredients: "Toor dal, mixed vegetables, tamarind, sambar powder, mustard seeds, curry leaves", method: "Cook dal and vegetables with tamarind and sambar powder, then temper with mustard and curry leaves." },
  { name: "Coconut chutney", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 tbsp (30 g)", kcal: 50, protein: 1, carbs: 2, fat: 4, ingredients: "Fresh coconut, roasted chana, green chilli, ginger, salt, curry leaves", method: "Grind everything with a little water and top with a mustard and curry leaf tempering." },
  { name: "Rasam", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 ml)", kcal: 45, protein: 2, carbs: 7, fat: 1, ingredients: "Tomato, tamarind, rasam powder, garlic, pepper, cumin, mustard, curry leaves", method: "Simmer tomato, tamarind and spices, then finish with a quick tempering and coriander." },
  { name: "Upma", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 bowl (200 g)", kcal: 230, protein: 6, carbs: 34, fat: 8, ingredients: "Semolina, onion, green chilli, mustard seeds, curry leaves, peanuts, oil", method: "Roast the semolina, temper the spices, add water and stir the semolina in until fluffy." },
  { name: "Poha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 plate (200 g)", kcal: 250, protein: 5, carbs: 44, fat: 6, ingredients: "Flattened rice, onion, potato, peanuts, turmeric, mustard seeds, lemon", method: "Rinse the poha, sauté onion and spices, fold in the poha and finish with lemon and coriander." },
  { name: "Vegetable pulao", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 cup (200 g)", kcal: 280, protein: 6, carbs: 48, fat: 7, ingredients: "Basmati rice, mixed vegetables, whole spices, ghee, salt", method: "Sauté whole spices and vegetables in ghee, add rice and water, and cook until fluffy." },
  { name: "Chicken biryani", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 520, protein: 27, carbs: 62, fat: 17, ingredients: "Basmati, chicken, yogurt, fried onion, biryani masala, mint, saffron, ghee", method: "Marinate chicken in yogurt and spices, layer with par-cooked rice, mint and fried onion, and steam on low heat." },
  { name: "Veg biryani", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 450, protein: 10, carbs: 68, fat: 14, ingredients: "Basmati, mixed vegetables, yogurt, fried onion, biryani masala, mint, ghee", method: "Layer spiced vegetables with par-cooked rice and mint, then seal and steam for 20 minutes." },
  { name: "Dhokla", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "4 pieces (120 g)", kcal: 160, protein: 6, carbs: 26, fat: 4, ingredients: "Gram flour, yogurt, ginger-chilli paste, fruit salt, mustard seeds", method: "Whisk a batter, add fruit salt and steam for 15 minutes, then pour over a mustard tempering." },
  { name: "Thepla", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "2 pieces", kcal: 200, protein: 6, carbs: 28, fat: 7, ingredients: "Wheat flour, fenugreek leaves, yogurt, turmeric, sesame, oil", method: "Knead everything into a dough, roll thin and cook with a little oil until speckled." },
  { name: "Pav bhaji", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "snack"], serving: "2 pav + 1 cup bhaji", kcal: 490, protein: 11, carbs: 70, fat: 18, ingredients: "Mixed vegetables, potato, tomato, butter, pav bhaji masala, pav", method: "Boil and mash the vegetables, cook in butter with masala until thick, then toast the pav in butter." },
  { name: "Vada pav", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1", kcal: 290, protein: 6, carbs: 41, fat: 11, ingredients: "Potato, gram flour, garlic chutney, pav, green chilli", method: "Coat spiced potato balls in gram-flour batter, fry until golden and tuck into a pav with chutney." },
  { name: "Misal pav", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "1 plate", kcal: 420, protein: 14, carbs: 56, fat: 15, ingredients: "Sprouted moth beans, onion, tomato, misal masala, farsan, pav", method: "Cook sprouts in a spicy masala, ladle into a plate, top with farsan and onion, and serve with pav." },
  { name: "Samosa", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 fried (60 g)", kcal: 260, protein: 4, carbs: 26, fat: 15, ingredients: "Flour, potato, peas, cumin, coriander, amchur, oil", method: "Fill a crisp dough cone with spiced potato and peas and fry slowly until golden. Baking cuts the calories." },
  { name: "Onion pakora", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "5 pieces (75 g)", kcal: 230, protein: 6, carbs: 20, fat: 14, ingredients: "Onion, gram flour, ajwain, chilli, salt, oil", method: "Mix sliced onion into a thick gram-flour batter and fry in small portions until crisp." },
  { name: "Sabudana khichdi", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 plate (200 g)", kcal: 350, protein: 4, carbs: 55, fat: 13, ingredients: "Soaked sago, potato, peanuts, cumin, green chilli, ghee", method: "Soak sabudana until soft, then toss in ghee with cumin, potato and crushed peanuts. A traditional Indian fasting-day dish." },
  { name: "Besan chilla", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 pieces", kcal: 230, protein: 11, carbs: 27, fat: 9, ingredients: "Gram flour, onion, tomato, green chilli, ajwain, coriander, oil", method: "Whisk a thin batter with chopped vegetables and cook on a lightly oiled tawa until golden." },
  { name: "Sprouts chaat", cuisine: "Indian", diet: "vegan", meals: ["snack", "salad", "detox"], serving: "1 bowl (150 g)", kcal: 130, protein: 9, carbs: 20, fat: 1, ingredients: "Moong sprouts, onion, tomato, cucumber, chaat masala, lemon", method: "Steam the sprouts briefly, toss with chopped vegetables, chaat masala and lemon." },
  { name: "Tandoori chicken", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner", "snack"], serving: "2 pieces (200 g)", kcal: 290, protein: 36, carbs: 5, fat: 14, ingredients: "Chicken, hung curd, tandoori masala, ginger-garlic, lemon, mustard oil", method: "Marinate in spiced curd for at least 4 hours, then grill or roast until charred at the edges." },
  { name: "Egg bhurji", cuisine: "Indian", diet: "eggetarian", meals: ["breakfast"], serving: "2 eggs", kcal: 220, protein: 13, carbs: 4, fat: 16, ingredients: "Eggs, onion, tomato, green chilli, turmeric, coriander, oil", method: "Sauté onion, tomato and spices, pour in beaten eggs and scramble softly." },
  { name: "Curd rice", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 g)", kcal: 260, protein: 8, carbs: 38, fat: 8, ingredients: "Cooked rice, curd, mustard seeds, curry leaves, ginger, green chilli", method: "Mash warm rice with curd and salt, then top with a mustard and curry leaf tempering." },
  { name: "Dahi / curd", cuisine: "Indian", diet: "vegetarian", meals: ["snack", "detox"], serving: "1 katori (100 g)", kcal: 60, protein: 3, carbs: 5, fat: 3, ingredients: "Milk, a spoon of curd as starter", method: "Warm milk to lukewarm, stir in a spoon of curd and leave in a warm place for 6 to 8 hours." },
  { name: "Cucumber raita", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (100 g)", kcal: 50, protein: 3, carbs: 5, fat: 2, ingredients: "Curd, cucumber, roasted cumin, salt, mint", method: "Whisk the curd, stir in grated cucumber and season with roasted cumin and salt." },
  { name: "Masala chai", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 cup (150 ml)", kcal: 90, protein: 2, carbs: 13, fat: 3, ingredients: "Tea leaves, milk, water, sugar, ginger, cardamom", method: "Simmer water with tea, ginger and cardamom, add milk and sugar and bring to a boil." },
  { name: "Sweet lassi", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 glass (250 ml)", kcal: 220, protein: 7, carbs: 34, fat: 6, ingredients: "Curd, sugar, cold water, cardamom", method: "Blend curd with water, sugar and cardamom until frothy and serve cold." },
  { name: "Gulab jamun", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 300, protein: 4, carbs: 45, fat: 12, ingredients: "Khoya or milk powder, flour, sugar, cardamom, ghee", method: "Shape soft dough balls, fry gently on low heat and soak in warm cardamom sugar syrup." },
  { name: "Kheer", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 katori (150 g)", kcal: 220, protein: 6, carbs: 32, fat: 8, ingredients: "Milk, rice, sugar, cardamom, nuts", method: "Simmer rice in milk, stirring often, until creamy, then sweeten and flavour with cardamom." },
  { name: "Margherita pizza", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "2 slices", kcal: 540, protein: 22, carbs: 66, fat: 20, ingredients: "Pizza dough, tomato sauce, mozzarella, basil, olive oil", method: "Stretch the dough, top with sauce and mozzarella and bake very hot until the crust blisters." },
  { name: "Spaghetti bolognese", cuisine: "Italian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 520, protein: 26, carbs: 65, fat: 16, ingredients: "Spaghetti, chicken or mutton mince, onion, carrot, tomato, garlic, olive oil", method: "Simmer the mince with onion, carrot and tomato for 30 minutes and toss through cooked spaghetti." },
  { name: "Pasta arrabbiata", cuisine: "Italian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 420, protein: 13, carbs: 72, fat: 9, ingredients: "Penne, tomato, garlic, dried chilli, olive oil, parsley", method: "Cook garlic and chilli in olive oil, add tomato and simmer, then toss with al dente penne." },
  { name: "Vegetable lasagna", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 piece (250 g)", kcal: 400, protein: 19, carbs: 35, fat: 20, ingredients: "Lasagna sheets, spinach, ricotta, tomato sauce, mozzarella", method: "Layer sheets with sauce, spinach and ricotta, cover with mozzarella and bake for 35 minutes." },
  { name: "Mushroom risotto", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 380, protein: 9, carbs: 56, fat: 12, ingredients: "Arborio rice, mushrooms, onion, stock, parmesan, butter", method: "Toast the rice, add hot stock a ladle at a time, stirring, and finish with butter and parmesan." },
  { name: "Caprese salad", cuisine: "Italian", diet: "vegetarian", meals: ["salad", "lunch"], serving: "1 plate (150 g)", kcal: 220, protein: 13, carbs: 5, fat: 17, ingredients: "Tomato, mozzarella, basil, olive oil, salt", method: "Layer sliced tomato and mozzarella with basil and dress with olive oil and salt." },
  { name: "Minestrone soup", cuisine: "Italian", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 130, protein: 5, carbs: 20, fat: 3, ingredients: "Beans, small pasta, carrot, celery, tomato, onion, olive oil", method: "Simmer the vegetables and beans in stock, add small pasta and cook until tender." },
  { name: "Chicken burrito", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 burrito", kcal: 600, protein: 30, carbs: 66, fat: 24, ingredients: "Flour tortilla, chicken, rice, beans, salsa, cheese", method: "Fill a warm tortilla with spiced chicken, rice, beans, salsa and cheese, then roll tightly." },
  { name: "Bean burrito bowl", cuisine: "Mexican", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 480, protein: 18, carbs: 70, fat: 14, ingredients: "Rice, black beans, corn, salsa, avocado, lime", method: "Layer warm rice and beans with corn, salsa and avocado and finish with lime." },
  { name: "Chicken tacos", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "2 tacos", kcal: 340, protein: 22, carbs: 32, fat: 13, ingredients: "Corn tortillas, chicken, onion, coriander, lime, salsa", method: "Cook spiced chicken, pile it into warm tortillas and top with onion, coriander and lime." },
  { name: "Veg tacos", cuisine: "Mexican", diet: "vegan", meals: ["lunch", "dinner"], serving: "2 tacos", kcal: 320, protein: 10, carbs: 42, fat: 13, ingredients: "Corn tortillas, beans, peppers, onion, avocado, salsa", method: "Sauté peppers and onion with spices, fill tortillas with beans and vegetables and top with salsa." },
  { name: "Chicken quesadilla", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner", "snack"], serving: "1 quesadilla", kcal: 550, protein: 30, carbs: 40, fat: 28, ingredients: "Tortilla, chicken, cheese, peppers, onion", method: "Fill a tortilla with chicken and cheese and toast in a pan until crisp and melted." },
  { name: "Veg fried rice", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 350, protein: 8, carbs: 58, fat: 9, ingredients: "Rice, carrot, beans, spring onion, soy sauce, garlic, oil", method: "Stir-fry the vegetables and garlic on high heat, add cold cooked rice and soy sauce and toss well." },
  { name: "Chicken fried rice", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 420, protein: 20, carbs: 58, fat: 12, ingredients: "Rice, chicken, egg, spring onion, soy sauce, garlic, oil", method: "Scramble the egg, stir-fry the chicken and garlic, then add cold rice and soy sauce." },
  { name: "Veg hakka noodles", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 380, protein: 9, carbs: 62, fat: 10, ingredients: "Noodles, cabbage, carrot, capsicum, soy sauce, vinegar, oil", method: "Boil the noodles, then stir-fry with vegetables and sauces on the highest heat." },
  { name: "Steamed veg momos", cuisine: "Asian", diet: "vegan", meals: ["snack"], serving: "6 pieces", kcal: 210, protein: 7, carbs: 38, fat: 3, ingredients: "Flour, cabbage, carrot, ginger, garlic, spring onion", method: "Fill thin dough with finely chopped seasoned vegetables and steam for 10 minutes." },
  { name: "Steamed chicken momos", cuisine: "Asian", diet: "non_vegetarian", meals: ["snack"], serving: "6 pieces", kcal: 250, protein: 15, carbs: 30, fat: 7, ingredients: "Flour, minced chicken, ginger, garlic, spring onion", method: "Fill dough with seasoned chicken mince and steam for 10 to 12 minutes." },
  { name: "Cucumber avocado sushi roll", cuisine: "Asian", diet: "vegan", meals: ["lunch", "snack"], serving: "8 pieces", kcal: 270, protein: 6, carbs: 50, fat: 5, ingredients: "Sushi rice, nori, cucumber, avocado, rice vinegar", method: "Spread seasoned rice on nori, add cucumber and avocado, roll tightly and slice." },
  { name: "Miso soup", cuisine: "Asian", diet: "pescatarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (240 ml)", kcal: 60, protein: 4, carbs: 6, fat: 2, ingredients: "Dashi (fish stock), miso paste, tofu, spring onion, wakame", method: "Warm the dashi, whisk in miso off the boil and add tofu and spring onion. Use a kombu-only dashi to make it vegan." },
  { name: "Chicken ramen", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 480, protein: 24, carbs: 60, fat: 16, ingredients: "Noodles, chicken, broth, egg, spring onion, soy sauce", method: "Simmer a savoury broth, cook noodles separately and top with chicken, egg and spring onion." },
  { name: "Thai green curry (chicken)", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 320, protein: 22, carbs: 10, fat: 22, ingredients: "Chicken, green curry paste, coconut milk, aubergine, Thai basil, fish sauce", method: "Fry the paste, add coconut milk and chicken and simmer until cooked, finishing with Thai basil." },
  { name: "Pad Thai (tofu)", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 550, protein: 20, carbs: 72, fat: 20, ingredients: "Rice noodles, tofu, egg, bean sprouts, peanuts, tamarind, lime", method: "Stir-fry noodles with tofu, egg and tamarind sauce, then top with sprouts, peanuts and lime." },
  { name: "Tom yum soup (prawn)", cuisine: "Asian", diet: "pescatarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl", kcal: 90, protein: 10, carbs: 6, fat: 3, ingredients: "Prawns, lemongrass, galangal, lime leaf, mushrooms, chilli, lime", method: "Simmer the aromatics in stock, add mushrooms and prawns and finish with lime juice." },
  { name: "Veg bibimbap", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 500, protein: 16, carbs: 82, fat: 12, ingredients: "Rice, spinach, carrot, mushrooms, egg, gochujang, sesame oil", method: "Top warm rice with seasoned vegetables and a fried egg, and mix in gochujang before eating." },
  { name: "Hummus with pita", cuisine: "Mediterranean", diet: "vegan", meals: ["snack", "detox"], serving: "3 tbsp + 1 pita", kcal: 280, protein: 9, carbs: 38, fat: 10, ingredients: "Chickpeas, tahini, lemon, garlic, olive oil, pita", method: "Blend chickpeas with tahini, lemon, garlic and olive oil until smooth and serve with warm pita." },
  { name: "Falafel", cuisine: "Mediterranean", diet: "vegan", meals: ["lunch", "dinner", "snack"], serving: "4 pieces (100 g)", kcal: 300, protein: 12, carbs: 28, fat: 16, ingredients: "Chickpeas, parsley, coriander, onion, garlic, cumin", method: "Blend soaked chickpeas with herbs and spices, shape into balls and bake or fry until golden." },
  { name: "Greek salad", cuisine: "Mediterranean", diet: "vegetarian", meals: ["salad", "lunch"], serving: "1 bowl (200 g)", kcal: 190, protein: 6, carbs: 10, fat: 14, ingredients: "Cucumber, tomato, olives, feta, red onion, olive oil", method: "Chop the vegetables, add olives and feta and dress with olive oil and oregano." },
  { name: "Chicken shawarma wrap", cuisine: "Mediterranean", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 wrap", kcal: 480, protein: 30, carbs: 42, fat: 20, ingredients: "Chicken, yogurt, shawarma spices, pita, garlic sauce, pickles", method: "Marinate and roast the chicken, slice thinly and wrap in pita with garlic sauce and pickles." },
  { name: "Shakshuka", cuisine: "Mediterranean", diet: "eggetarian", meals: ["breakfast"], serving: "2 eggs", kcal: 250, protein: 15, carbs: 13, fat: 16, ingredients: "Eggs, tomato, capsicum, onion, garlic, cumin, paprika", method: "Simmer a spiced tomato and pepper sauce, make wells, crack in eggs and cover until set." },
  { name: "Tabbouleh", cuisine: "Mediterranean", diet: "vegan", meals: ["salad", "lunch"], serving: "1 cup (150 g)", kcal: 150, protein: 3, carbs: 17, fat: 8, ingredients: "Parsley, bulgur, tomato, mint, lemon, olive oil", method: "Soak bulgur, then mix with plenty of chopped parsley, tomato, mint, lemon and olive oil." },
  { name: "Grilled chicken breast", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "150 g", kcal: 250, protein: 46, carbs: 0, fat: 6, ingredients: "Chicken breast, olive oil, garlic, lemon, pepper", method: "Marinate briefly and grill 5 to 6 minutes a side until cooked through, then rest before slicing." },
  { name: "Veg grilled sandwich", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "lunch", "snack"], serving: "1 (2 slices)", kcal: 280, protein: 9, carbs: 38, fat: 10, ingredients: "Bread, cucumber, tomato, cheese, green chutney, butter", method: "Layer vegetables, cheese and chutney between slices and toast until golden." },
  { name: "Plain omelette", cuisine: "Western", diet: "eggetarian", meals: ["breakfast"], serving: "2 eggs", kcal: 200, protein: 13, carbs: 1, fat: 16, ingredients: "Eggs, butter, salt, pepper, herbs", method: "Whisk the eggs, pour into a buttered pan, fold when nearly set and slide onto a plate." },
  { name: "Avocado toast", cuisine: "Western", diet: "vegan", meals: ["breakfast"], serving: "1 slice", kcal: 240, protein: 6, carbs: 26, fat: 13, ingredients: "Sourdough, avocado, lemon, chilli flakes, salt", method: "Toast the bread, mash the avocado with lemon and salt and spread it on top." },
  { name: "Chicken Caesar salad", cuisine: "Western", diet: "non_vegetarian", meals: ["salad", "lunch"], serving: "1 bowl", kcal: 420, protein: 30, carbs: 16, fat: 26, ingredients: "Romaine, grilled chicken, parmesan, croutons, Caesar dressing", method: "Toss the lettuce with dressing, top with sliced chicken, parmesan and croutons." },
  { name: "Pancakes with syrup", cuisine: "Western", diet: "eggetarian", meals: ["breakfast"], serving: "3 pancakes", kcal: 450, protein: 8, carbs: 80, fat: 9, ingredients: "Flour, milk, egg, baking powder, sugar, maple syrup", method: "Whisk a thick batter, cook small rounds until bubbles appear, flip and serve with syrup." },
  { name: "Chicken burger", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 burger", kcal: 480, protein: 28, carbs: 40, fat: 22, ingredients: "Bun, chicken patty, cheese, lettuce, tomato, onion", method: "Grill the patty, melt cheese on top and stack in a toasted bun with the vegetables." },
  { name: "French fries", cuisine: "Western", diet: "vegan", meals: ["snack"], serving: "1 medium (115 g)", kcal: 365, protein: 4, carbs: 48, fat: 17, ingredients: "Potatoes, oil, salt", method: "Cut, soak and dry the potatoes, then fry until golden. Oven-baking cuts the fat." },
  { name: "Overnight oats", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 jar", kcal: 320, protein: 12, carbs: 46, fat: 10, ingredients: "Rolled oats, milk, yogurt, chia seeds, fruit", method: "Mix everything in a jar and chill overnight; top with fresh fruit in the morning." },
  { name: "Greek yogurt with berries", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "snack", "detox"], serving: "1 bowl (200 g)", kcal: 180, protein: 17, carbs: 18, fat: 4, ingredients: "Greek yogurt, berries, honey", method: "Spoon the yogurt into a bowl and top with berries and a little honey." },
  { name: "Mac and cheese", cuisine: "Western", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 cup (200 g)", kcal: 380, protein: 14, carbs: 40, fat: 18, ingredients: "Macaroni, milk, cheddar, butter, flour", method: "Make a cheese sauce with butter, flour, milk and cheddar and fold through the cooked macaroni." },
  { name: "Grilled salmon", cuisine: "Western", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "150 g", kcal: 310, protein: 33, carbs: 0, fat: 19, ingredients: "Salmon fillet, lemon, garlic, olive oil, dill", method: "Season the fillet and grill or pan-sear about 4 minutes a side until it flakes." },
  { name: "Banana peanut smoothie", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "snack", "detox"], serving: "1 glass (300 ml)", kcal: 320, protein: 10, carbs: 48, fat: 10, ingredients: "Banana, milk, peanut butter, honey, ice", method: "Blend everything until smooth and serve cold." },
  { name: "Chicken soup", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 130, protein: 12, carbs: 10, fat: 4, ingredients: "Chicken, carrot, celery, onion, garlic, herbs", method: "Simmer chicken with vegetables and herbs until tender, then shred the meat back into the broth." },
  { name: "Oats porridge with milk", cuisine: "Basics", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 bowl (40 g oats)", kcal: 300, protein: 12, carbs: 42, fat: 9, ingredients: "Rolled oats, milk, honey, fruit", method: "Simmer oats in milk for 5 minutes, stirring, then top with fruit." },
  { name: "Boiled egg", cuisine: "Basics", diet: "eggetarian", meals: ["breakfast", "snack"], serving: "1 large", kcal: 75, protein: 6, carbs: 1, fat: 5, ingredients: "", method: "" },
  { name: "Banana", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "1 medium", kcal: 105, protein: 1, carbs: 27, fat: 0, ingredients: "", method: "" },
  { name: "Apple", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "1 medium", kcal: 95, protein: 0, carbs: 25, fat: 0, ingredients: "", method: "" },
  { name: "Papaya", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "1 cup (150 g)", kcal: 60, protein: 1, carbs: 15, fat: 0, ingredients: "", method: "" },
  { name: "Almonds", cuisine: "Basics", diet: "vegan", meals: ["snack"], serving: "10 nuts (12 g)", kcal: 70, protein: 3, carbs: 3, fat: 6, ingredients: "", method: "" },
  { name: "Peanuts", cuisine: "Basics", diet: "vegan", meals: ["snack"], serving: "30 g", kcal: 170, protein: 8, carbs: 5, fat: 14, ingredients: "", method: "" },
  { name: "Roasted chana", cuisine: "Basics", diet: "vegan", meals: ["snack"], serving: "30 g", kcal: 110, protein: 6, carbs: 18, fat: 2, ingredients: "", method: "" },
  { name: "Whole milk", cuisine: "Basics", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "1 glass (250 ml)", kcal: 150, protein: 8, carbs: 12, fat: 8, ingredients: "", method: "" },
  { name: "Boiled sweet potato", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "150 g", kcal: 130, protein: 2, carbs: 30, fat: 0, ingredients: "", method: "" },
  { name: "Ghee", cuisine: "Basics", diet: "vegetarian", meals: ["detox"], serving: "1 tsp (5 g)", kcal: 45, protein: 0, carbs: 0, fat: 5, ingredients: "", method: "" },
];

// Batch 2: more regional Indian dishes (Gujarati, Bengali, Punjabi,
// Maharashtrian, Rajasthani, South Indian, street food, sweets, detox
// drinks) plus more global mains, bowls and salads adapted for the
// Indian palate. No beef.
const BATCH_2: Dish[] = [
  { name: "Uttapam", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 medium", kcal: 180, protein: 5, carbs: 30, fat: 4, ingredients: "Dosa batter, onion, tomato, green chilli, oil", method: "Spread thick batter on a hot tawa, scatter chopped onion, tomato and chilli on top, and cook both sides until golden." },
  { name: "Rava idli", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast"], serving: "3 pieces (150 g)", kcal: 200, protein: 5, carbs: 32, fat: 6, ingredients: "Semolina, curd, mustard seeds, curry leaves, cashew, oil", method: "Temper semolina with mustard seeds and cashew, mix in curd and steam in moulds until soft and fluffy." },
  { name: "Dahi vada", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 220, protein: 8, carbs: 28, fat: 8, ingredients: "Urad dal vada, curd, tamarind chutney, roasted cumin", method: "Soak fried lentil dumplings in water to soften, then submerge in whisked curd and top with chutney and spices." },
  { name: "Medu vada", cuisine: "Indian", diet: "vegan", meals: ["snack", "breakfast"], serving: "2 pieces", kcal: 190, protein: 6, carbs: 22, fat: 9, ingredients: "Urad dal, ginger, curry leaves, pepper, oil", method: "Grind soaked urad dal to a fluffy batter, shape into rings and deep-fry until golden and crisp." },
  { name: "Appam", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 pieces", kcal: 210, protein: 4, carbs: 40, fat: 4, ingredients: "Rice, coconut milk, yeast, salt", method: "Ferment a rice and coconut milk batter, then swirl in a curved pan so the edges turn lacy and thin." },
  { name: "Puttu", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 cup", kcal: 220, protein: 5, carbs: 45, fat: 2, ingredients: "Rice flour, grated coconut, salt, water", method: "Layer rice flour and coconut in a steamer mould and steam until soft, then serve with banana or chickpea curry." },
  { name: "Lemon rice", cuisine: "Indian", diet: "vegan", meals: ["lunch"], serving: "1 cup (200 g)", kcal: 260, protein: 5, carbs: 45, fat: 7, ingredients: "Rice, lemon juice, peanuts, mustard seeds, curry leaves, turmeric, oil", method: "Temper mustard seeds, peanuts and curry leaves in oil, then toss through cooked rice with lemon juice and turmeric." },
  { name: "Tamarind rice", cuisine: "Indian", diet: "vegan", meals: ["lunch"], serving: "1 cup (200 g)", kcal: 280, protein: 5, carbs: 48, fat: 8, ingredients: "Rice, tamarind, jaggery, peanuts, sesame, curry leaves, oil", method: "Cook a thick tamarind-jaggery paste with spices, then mix through cooked rice with a peanut and sesame tempering." },
  { name: "Coconut rice", cuisine: "Indian", diet: "vegan", meals: ["lunch"], serving: "1 cup (200 g)", kcal: 300, protein: 5, carbs: 42, fat: 12, ingredients: "Rice, fresh coconut, mustard seeds, curry leaves, cashew, oil", method: "Toast grated coconut and cashews in a tempering, then fold through warm cooked rice." },
  { name: "Bisi bele bath", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 320, protein: 9, carbs: 50, fat: 9, ingredients: "Rice, toor dal, mixed vegetables, tamarind, bisi bele bath powder, ghee", method: "Cook rice, dal and vegetables together with tamarind and spice powder until thick and porridge-like, then finish with ghee." },
  { name: "Ragi mudde", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "2 balls", kcal: 220, protein: 6, carbs: 45, fat: 2, ingredients: "Finger millet flour, water, salt", method: "Stir finger millet flour into boiling water until it forms a stiff dough, then shape into smooth balls." },
  { name: "Pesarattu", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 medium", kcal: 190, protein: 9, carbs: 28, fat: 5, ingredients: "Whole moong dal, rice, ginger, green chilli, oil", method: "Grind soaked moong dal and rice into a batter, spread thin on a tawa like a dosa and cook until crisp." },
  { name: "Avial", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 160, protein: 4, carbs: 14, fat: 10, ingredients: "Mixed vegetables, coconut, curd, cumin, curry leaves, coconut oil", method: "Simmer mixed vegetables until just tender, then fold through a ground coconut and curd paste." },
  { name: "Kadhi pakora", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (200 g)", kcal: 260, protein: 9, carbs: 26, fat: 13, ingredients: "Gram flour, curd, pakora, turmeric, cumin, curry leaves", method: "Simmer a curd and gram flour base until thickened, temper with cumin, and drop in fried gram-flour pakoras." },
  { name: "Undhiyu", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 240, protein: 7, carbs: 28, fat: 11, ingredients: "Mixed winter vegetables, beans, fenugreek dumplings, oil, spices", method: "Slow-cook a mix of winter vegetables, beans and small dumplings together with ginger, chilli and coriander." },
  { name: "Khandvi", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "6 rolls", kcal: 150, protein: 6, carbs: 18, fat: 6, ingredients: "Gram flour, curd, ginger, mustard seeds, curry leaves", method: "Cook a smooth gram-flour and curd batter until thick, spread thin, roll once cool and temper with mustard seeds." },
  { name: "Handvo", cuisine: "Indian", diet: "vegetarian", meals: ["snack", "breakfast"], serving: "1 piece (100 g)", kcal: 220, protein: 7, carbs: 30, fat: 8, ingredients: "Rice, mixed lentils, curd, bottle gourd, sesame, oil", method: "Ferment a rice-lentil-curd batter with grated vegetables, then bake or pan-cook until crisp outside and soft within." },
  { name: "Fafda", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "4 pieces", kcal: 230, protein: 5, carbs: 26, fat: 12, ingredients: "Gram flour, carom seeds, oil, papaya soda", method: "Roll a stiff gram-flour dough into thin strips and deep-fry until crisp and pale golden." },
  { name: "Gujarati kadhi", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 130, protein: 4, carbs: 16, fat: 5, ingredients: "Curd, gram flour, jaggery, curry leaves, mustard seeds", method: "Whisk curd with gram flour and a little jaggery, simmer gently and temper with mustard seeds and curry leaves." },
  { name: "Litti chokha", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "2 pieces + chokha", kcal: 380, protein: 10, carbs: 50, fat: 15, ingredients: "Wheat flour, roasted sattu, mashed eggplant and potato, ghee, spices", method: "Stuff a wheat dough ball with spiced roasted gram flour, roast over embers, and serve with mashed spiced vegetables." },
  { name: "Dal baati churma", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "2 baati + dal", kcal: 480, protein: 12, carbs: 55, fat: 22, ingredients: "Wheat flour, ghee, mixed dal, jaggery, spices", method: "Bake firm wheat dough balls until crisp, crush with ghee and jaggery for churma, and serve with a spiced dal." },
  { name: "Ker sangri", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (120 g)", kcal: 140, protein: 4, carbs: 12, fat: 9, ingredients: "Dried desert beans and berries, dry spice masala, oil", method: "Soak and cook the dried beans and berries, then stir-fry with a dry Rajasthani spice blend." },
  { name: "Machher jhol", cuisine: "Indian", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "1 bowl (200 g)", kcal: 220, protein: 22, carbs: 6, fat: 12, ingredients: "Fish, potato, turmeric, cumin, mustard oil, panch phoron", method: "Fry lightly spiced fish pieces, then simmer in a thin turmeric and cumin gravy with potato." },
  { name: "Shorshe ilish", cuisine: "Indian", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "1 piece with gravy", kcal: 260, protein: 20, carbs: 4, fat: 18, ingredients: "Oily fish, mustard paste, green chilli, mustard oil, turmeric", method: "Simmer fish gently in a pungent mustard paste gravy, finished with a drizzle of raw mustard oil." },
  { name: "Cholar dal", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 200, protein: 9, carbs: 28, fat: 6, ingredients: "Split Bengal gram, coconut, bay leaf, ghee, whole spices", method: "Cook the dal until soft, then temper with bay leaf, whole spices and a few pieces of coconut fried in ghee." },
  { name: "Luchi", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast"], serving: "2 pieces", kcal: 220, protein: 4, carbs: 26, fat: 11, ingredients: "Refined or wheat flour, ghee, salt", method: "Roll small dough rounds and deep-fry until they puff into light, golden discs." },
  { name: "Aloo posto", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 210, protein: 4, carbs: 22, fat: 12, ingredients: "Potato, poppy seed paste, green chilli, mustard oil, nigella seeds", method: "Cook potatoes in a ground poppy seed paste with nigella seeds and mustard oil until soft." },
  { name: "Chingri malai curry", cuisine: "Indian", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "1 bowl (200 g)", kcal: 290, protein: 18, carbs: 8, fat: 20, ingredients: "Prawns, coconut milk, onion, ginger, whole garam masala, mustard oil", method: "Lightly fry the prawns, then simmer in a coconut milk and onion gravy flavoured with whole spices." },
  { name: "Rogan josh", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 360, protein: 24, carbs: 8, fat: 26, ingredients: "Mutton, curd, Kashmiri chilli, fennel, ginger powder, mustard oil", method: "Slow-cook mutton in a curd and Kashmiri chilli gravy until deeply red and tender." },
  { name: "Dum aloo (Kashmiri)", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 240, protein: 4, carbs: 26, fat: 14, ingredients: "Baby potatoes, curd, Kashmiri chilli, fennel, ginger powder, mustard oil", method: "Fry whole baby potatoes, then simmer in a curd and Kashmiri chilli gravy until infused." },
  { name: "Modak", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "3 pieces", kcal: 240, protein: 4, carbs: 34, fat: 10, ingredients: "Rice flour, jaggery, grated coconut, ghee, cardamom", method: "Steam rice flour dumplings filled with a sweet coconut-jaggery mixture until glossy and soft." },
  { name: "Puran poli", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 piece", kcal: 260, protein: 6, carbs: 42, fat: 8, ingredients: "Wheat flour, chana dal, jaggery, cardamom, ghee", method: "Stuff a sweet lentil-jaggery filling inside a soft dough, roll gently and cook on a tawa with ghee." },
  { name: "Thalipeeth", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 piece", kcal: 210, protein: 6, carbs: 28, fat: 8, ingredients: "Mixed flours (jowar, bajra, besan), onion, chilli, coriander, oil", method: "Mix a multigrain dough with chopped onion and spices, pat directly onto a hot tawa and cook with a little oil." },
  { name: "Zunka", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 170, protein: 6, carbs: 14, fat: 10, ingredients: "Gram flour, onion, garlic, green chilli, oil", method: "Toast gram flour with sautéed onion and garlic until it turns into a dry, crumbly curry." },
  { name: "Varan bhaat", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 260, protein: 9, carbs: 42, fat: 6, ingredients: "Toor dal, rice, ghee, cumin, turmeric", method: "Cook plain turmeric dal until soft and serve over warm rice with a spoon of ghee." },
  { name: "Sattu paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 piece", kcal: 260, protein: 8, carbs: 34, fat: 10, ingredients: "Wheat flour, roasted gram flour, onion, pickle spices, oil", method: "Stuff a spiced roasted-gram filling into dough, roll gently and cook with a little oil until golden." },
  { name: "Chole bhature", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 plate", kcal: 520, protein: 14, carbs: 62, fat: 22, ingredients: "Chickpeas, onion, tomato, chole masala, refined flour, curd, oil", method: "Simmer chickpeas in a tangy onion-tomato masala and serve with a puffed, deep-fried leavened bread." },
  { name: "Amritsari kulcha", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 piece", kcal: 320, protein: 8, carbs: 46, fat: 11, ingredients: "Refined flour, curd, potato filling, butter", method: "Stuff a spiced potato filling into a soft leavened dough, roll gently and cook in a tandoor or hot tawa with butter." },
  { name: "Sarson ka saag", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g) + roti", kcal: 220, protein: 6, carbs: 18, fat: 14, ingredients: "Mustard greens, spinach, maize flour, ginger-garlic, ghee", method: "Simmer mustard and spinach leaves until soft, mash coarsely, thicken with a little maize flour and finish with ghee." },
  { name: "Paneer tikka", cuisine: "Indian", diet: "vegetarian", meals: ["snack", "lunch", "dinner"], serving: "6 pieces", kcal: 280, protein: 16, carbs: 8, fat: 20, ingredients: "Paneer, curd, tikka masala, capsicum, onion, mustard oil", method: "Marinate paneer and vegetables in spiced curd, then grill or roast until lightly charred." },
  { name: "Chicken tikka", cuisine: "Indian", diet: "non_vegetarian", meals: ["snack", "lunch", "dinner"], serving: "6 pieces (150 g)", kcal: 260, protein: 30, carbs: 4, fat: 13, ingredients: "Chicken, curd, tikka masala, ginger-garlic, mustard oil", method: "Marinate chicken pieces in spiced curd for a few hours, then grill until charred at the edges and cooked through." },
  { name: "Fish tikka", cuisine: "Indian", diet: "pescatarian", meals: ["snack", "lunch", "dinner"], serving: "150 g", kcal: 230, protein: 26, carbs: 3, fat: 12, ingredients: "Firm white fish, curd, ajwain, chilli, ginger-garlic, mustard oil", method: "Marinate fish chunks briefly in spiced curd, then grill on skewers until just cooked through." },
  { name: "Malai kofta", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "3 kofta with gravy", kcal: 380, protein: 10, carbs: 26, fat: 26, ingredients: "Paneer, potato, cashew, cream, tomato gravy", method: "Shape a paneer and potato mixture into balls, fry lightly, and serve in a rich cashew-tomato gravy." },
  { name: "Kadai paneer", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 310, protein: 13, carbs: 14, fat: 22, ingredients: "Paneer, capsicum, onion, tomato, kadai masala, oil", method: "Cook a coarsely ground onion-tomato masala with capsicum, then toss in paneer cubes just before serving." },
  { name: "Kadai chicken", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 290, protein: 25, carbs: 9, fat: 17, ingredients: "Chicken, capsicum, onion, tomato, kadai masala, oil", method: "Cook chicken in a freshly ground kadai masala with capsicum and onion until the sauce clings to the pieces." },
  { name: "Mutton curry", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 340, protein: 24, carbs: 8, fat: 24, ingredients: "Mutton, onion, tomato, ginger-garlic, whole spices, oil", method: "Brown the mutton with onions and whole spices, then slow-cook until tender in a thick masala." },
  { name: "Keema matar", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 300, protein: 22, carbs: 10, fat: 19, ingredients: "Chicken mince, green peas, onion, tomato, spices, oil", method: "Cook minced chicken with onion and tomato masala, add green peas and simmer until the peas are tender." },
  { name: "Chicken 65", cuisine: "Indian", diet: "non_vegetarian", meals: ["snack"], serving: "150 g", kcal: 320, protein: 26, carbs: 12, fat: 18, ingredients: "Chicken, curd, chilli, ginger-garlic, curry leaves, oil", method: "Marinate bite-sized chicken in spiced curd, fry until crisp, and toss with curry leaves and green chilli." },
  { name: "Gobi manchurian", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "1 plate (200 g)", kcal: 280, protein: 6, carbs: 36, fat: 12, ingredients: "Cauliflower, cornflour, soy sauce, garlic, spring onion, oil", method: "Fry battered cauliflower florets until crisp, then toss in a garlicky soy-based sauce." },
  { name: "Paneer manchurian", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 plate (200 g)", kcal: 340, protein: 15, carbs: 30, fat: 18, ingredients: "Paneer, cornflour, soy sauce, garlic, capsicum, oil", method: "Lightly fry cubed paneer, then toss with capsicum in a garlic-soy sauce until glossy." },
  { name: "Chilli paneer", cuisine: "Indian", diet: "vegetarian", meals: ["snack", "lunch", "dinner"], serving: "1 plate (200 g)", kcal: 350, protein: 15, carbs: 26, fat: 20, ingredients: "Paneer, capsicum, onion, soy sauce, chilli sauce, cornflour, oil", method: "Fry battered paneer until golden, then stir-fry with capsicum, onion and a spicy soy sauce." },
  { name: "Chilli chicken", cuisine: "Indian", diet: "non_vegetarian", meals: ["snack", "lunch", "dinner"], serving: "1 plate (200 g)", kcal: 340, protein: 26, carbs: 20, fat: 17, ingredients: "Chicken, capsicum, onion, soy sauce, chilli sauce, cornflour, oil", method: "Fry battered chicken until crisp, then toss with capsicum and onion in a spicy soy-chilli sauce." },
  { name: "Dahi bhalla", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 230, protein: 8, carbs: 30, fat: 8, ingredients: "Urad dal vada, curd, tamarind and mint chutney, spices", method: "Soak fried lentil dumplings in water, squeeze gently, then layer with whisked curd and chutneys." },
  { name: "Pani puri", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "6 pieces", kcal: 180, protein: 4, carbs: 32, fat: 4, ingredients: "Semolina puri, tamarind water, mint water, potato, chickpeas, spices", method: "Fill crisp hollow puris with spiced potato and chickpeas, then top with tangy mint and tamarind water just before eating." },
  { name: "Bhel puri", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "1 plate (150 g)", kcal: 220, protein: 5, carbs: 36, fat: 6, ingredients: "Puffed rice, sev, potato, onion, tomato, tamarind chutney", method: "Toss puffed rice, crunchy sev and chopped vegetables with tangy tamarind and mint chutneys just before serving." },
  { name: "Sev puri", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "6 pieces", kcal: 240, protein: 5, carbs: 34, fat: 10, ingredients: "Puri, potato, onion, sev, tamarind and mint chutney", method: "Top small crisp puris with spiced potato, chutneys and a generous scatter of crunchy sev." },
  { name: "Dahi puri", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "6 pieces", kcal: 260, protein: 6, carbs: 34, fat: 11, ingredients: "Puri, potato, curd, sev, tamarind and mint chutney", method: "Fill crisp puris with spiced potato, top with whisked curd, chutneys and sev." },
  { name: "Ragda pattice", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "1 plate", kcal: 320, protein: 9, carbs: 48, fat: 10, ingredients: "Potato patties, white peas curry, tamarind and mint chutney, onion", method: "Pan-fry spiced potato patties and serve smothered in a mildly spiced white pea curry and chutneys." },
  { name: "Kachori", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "2 pieces", kcal: 260, protein: 6, carbs: 30, fat: 13, ingredients: "Refined flour, moong or urad dal filling, fennel, asafoetida, oil", method: "Stuff a spiced lentil filling into small dough balls and deep-fry until flaky and golden." },
  { name: "Khaman", cuisine: "Indian", diet: "vegan", meals: ["snack", "breakfast"], serving: "4 pieces (120 g)", kcal: 170, protein: 6, carbs: 26, fat: 5, ingredients: "Gram flour, fruit salt, ginger-chilli paste, mustard seeds", method: "Steam a light gram-flour batter until spongy, cut into squares and top with a mustard seed tempering." },
  { name: "Sundal", cuisine: "Indian", diet: "vegan", meals: ["snack", "detox"], serving: "1 katori (100 g)", kcal: 140, protein: 7, carbs: 20, fat: 4, ingredients: "Boiled chickpeas or peanuts, coconut, mustard seeds, curry leaves", method: "Toss boiled legumes with a light mustard-curry leaf tempering and fresh grated coconut." },
  { name: "Murukku", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "6 pieces (40 g)", kcal: 190, protein: 3, carbs: 20, fat: 11, ingredients: "Rice flour, urad dal flour, sesame, ajwain, oil", method: "Pipe a spiced rice flour dough into spirals and deep-fry until crisp and golden." },
  { name: "Chakli", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "6 pieces (40 g)", kcal: 190, protein: 4, carbs: 22, fat: 10, ingredients: "Rice flour, gram flour, sesame, ajwain, oil", method: "Pipe a spiced flour dough into spirals and fry until crunchy throughout." },
  { name: "Mathri", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "4 pieces", kcal: 220, protein: 4, carbs: 24, fat: 12, ingredients: "Refined flour, ghee, ajwain, pepper", method: "Knead a firm dough with ghee and spices, roll into discs and fry until flaky and golden." },
  { name: "Nankhatai", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 200, protein: 3, carbs: 24, fat: 10, ingredients: "Refined flour, ghee, sugar, cardamom", method: "Cream ghee and sugar, fold in flour and cardamom, shape and bake until pale golden and crumbly." },
  { name: "Besan laddoo", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 220, protein: 4, carbs: 26, fat: 11, ingredients: "Gram flour, ghee, sugar, cardamom", method: "Roast gram flour in ghee until fragrant, mix with sugar and cardamom, and shape into balls while warm." },
  { name: "Coconut laddoo", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 190, protein: 3, carbs: 24, fat: 9, ingredients: "Desiccated coconut, condensed milk, cardamom", method: "Cook coconut with condensed milk until it comes together, then shape into balls while still warm." },
  { name: "Til chikki", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "2 pieces (30 g)", kcal: 160, protein: 4, carbs: 16, fat: 9, ingredients: "Sesame seeds, jaggery", method: "Melt jaggery to a hard-crack stage, stir in roasted sesame seeds and set into a thin slab before cutting." },
  { name: "Ragi porridge", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 bowl", kcal: 220, protein: 7, carbs: 34, fat: 6, ingredients: "Finger millet flour, milk or buttermilk, jaggery", method: "Cook finger millet flour in milk or buttermilk until smooth, sweetening lightly with jaggery." },
  { name: "Bajra khichdi", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (220 g)", kcal: 260, protein: 8, carbs: 40, fat: 8, ingredients: "Pearl millet, moong dal, turmeric, cumin, ghee", method: "Cook pearl millet and moong dal together with turmeric until soft, then finish with a cumin-ghee tempering." },
  { name: "Jowar roti", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 medium", kcal: 110, protein: 3, carbs: 22, fat: 1, ingredients: "Sorghum flour, hot water, salt", method: "Knead sorghum flour with hot water into a soft dough, pat into a round and cook on a hot tawa on both sides." },
  { name: "Kachumber salad", cuisine: "Indian", diet: "vegan", meals: ["salad"], serving: "1 bowl (150 g)", kcal: 60, protein: 2, carbs: 12, fat: 0, ingredients: "Cucumber, tomato, onion, lemon, coriander", method: "Finely chop the vegetables, toss with lemon juice, salt and coriander just before serving." },
  { name: "Sprouts pomegranate salad", cuisine: "Indian", diet: "vegan", meals: ["salad", "detox"], serving: "1 bowl (150 g)", kcal: 150, protein: 9, carbs: 22, fat: 2, ingredients: "Moong sprouts, pomegranate, cucumber, lemon, chaat masala", method: "Toss steamed sprouts with pomegranate arils, cucumber and a squeeze of lemon." },
  { name: "Chana chaat", cuisine: "Indian", diet: "vegan", meals: ["salad", "snack", "detox"], serving: "1 bowl (150 g)", kcal: 160, protein: 9, carbs: 24, fat: 3, ingredients: "Boiled chickpeas, onion, tomato, cucumber, chaat masala, lemon", method: "Toss boiled chickpeas with chopped vegetables, lemon juice and chaat masala." },
  { name: "Chaas", cuisine: "Indian", diet: "vegetarian", meals: ["detox", "snack"], serving: "1 glass (250 ml)", kcal: 60, protein: 3, carbs: 5, fat: 2, ingredients: "Curd, water, roasted cumin, mint, salt", method: "Whisk curd with water until frothy, then season with roasted cumin, mint and a pinch of salt." },
  { name: "Jeera water", cuisine: "Indian", diet: "vegan", meals: ["detox"], serving: "1 glass (250 ml)", kcal: 10, protein: 0, carbs: 2, fat: 0, ingredients: "Cumin seeds, water", method: "Soak or lightly boil cumin seeds in water, strain and sip through the morning." },
  { name: "Amla juice", cuisine: "Indian", diet: "vegan", meals: ["detox"], serving: "1 small glass (100 ml)", kcal: 45, protein: 0, carbs: 11, fat: 0, ingredients: "Indian gooseberry, water, a little honey", method: "Blend fresh amla with water, strain if preferred, and sweeten lightly with honey." },
  { name: "ABC juice", cuisine: "Indian", diet: "vegan", meals: ["detox"], serving: "1 glass (250 ml)", kcal: 130, protein: 2, carbs: 30, fat: 0, ingredients: "Apple, beetroot, carrot", method: "Juice or blend the apple, beetroot and carrot together and drink fresh." },
  { name: "Green detox smoothie", cuisine: "Indian", diet: "vegan", meals: ["detox", "breakfast"], serving: "1 glass (300 ml)", kcal: 140, protein: 3, carbs: 30, fat: 1, ingredients: "Spinach, apple, ginger, lemon, water", method: "Blend spinach, apple, ginger and lemon with a little water until smooth." },
  { name: "Turmeric latte", cuisine: "Indian", diet: "vegetarian", meals: ["detox", "snack"], serving: "1 cup (200 ml)", kcal: 90, protein: 4, carbs: 10, fat: 4, ingredients: "Milk, turmeric, black pepper, cinnamon, honey", method: "Warm milk with turmeric, a pinch of black pepper and cinnamon, then sweeten lightly with honey." },
  { name: "Watermelon juice", cuisine: "Basics", diet: "vegan", meals: ["detox", "snack"], serving: "1 glass (250 ml)", kcal: 80, protein: 1, carbs: 20, fat: 0, ingredients: "", method: "" },
  { name: "Shepherd's pie (chicken)", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 portion (300 g)", kcal: 420, protein: 24, carbs: 38, fat: 18, ingredients: "Chicken or mutton mince, mashed potato, carrot, peas, onion", method: "Simmer minced chicken with vegetables in a light gravy, top with mashed potato and bake until golden." },
  { name: "Ratatouille", cuisine: "Western", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 g)", kcal: 160, protein: 4, carbs: 20, fat: 8, ingredients: "Aubergine, courgette, capsicum, tomato, garlic, olive oil", method: "Slow-cook layered summer vegetables with garlic and olive oil until soft and richly flavoured." },
  { name: "Baba ganoush", cuisine: "Mediterranean", diet: "vegan", meals: ["snack", "detox"], serving: "3 tbsp", kcal: 120, protein: 3, carbs: 8, fat: 9, ingredients: "Roasted aubergine, tahini, lemon, garlic, olive oil", method: "Roast aubergine until smoky and soft, then blend with tahini, lemon and garlic." },
  { name: "Fattoush salad", cuisine: "Mediterranean", diet: "vegan", meals: ["salad", "lunch"], serving: "1 bowl (200 g)", kcal: 180, protein: 4, carbs: 20, fat: 10, ingredients: "Mixed greens, cucumber, tomato, toasted pita, sumac, olive oil", method: "Toss crisp greens and vegetables with toasted pita chips and a tangy sumac dressing." },
  { name: "Koshari", cuisine: "Mediterranean", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl (300 g)", kcal: 480, protein: 15, carbs: 85, fat: 9, ingredients: "Rice, lentils, macaroni, crispy onion, tomato sauce, garlic vinegar", method: "Layer rice, lentils and macaroni, top with a spiced tomato sauce, garlic vinegar and crisp fried onions." },
  { name: "Vegetable paella", cuisine: "Mediterranean", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 380, protein: 9, carbs: 68, fat: 8, ingredients: "Rice, saffron, capsicum, tomato, green beans, olive oil", method: "Toast rice with saffron and vegetables in a wide pan, then simmer without stirring until the rice is tender." },
  { name: "Gazpacho", cuisine: "Mediterranean", diet: "vegan", meals: ["salad", "detox", "lunch"], serving: "1 bowl (250 ml)", kcal: 90, protein: 2, carbs: 14, fat: 3, ingredients: "Tomato, cucumber, capsicum, garlic, olive oil, vinegar", method: "Blend ripe tomatoes with cucumber, capsicum and garlic, then chill well before serving." },
  { name: "Quinoa salad", cuisine: "Western", diet: "vegan", meals: ["salad", "lunch", "detox"], serving: "1 bowl (200 g)", kcal: 260, protein: 8, carbs: 36, fat: 9, ingredients: "Quinoa, cucumber, tomato, chickpeas, lemon, olive oil", method: "Toss cooked quinoa with chopped vegetables, chickpeas and a lemon-olive oil dressing." },
  { name: "Buddha bowl", cuisine: "Western", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl (350 g)", kcal: 420, protein: 14, carbs: 58, fat: 15, ingredients: "Brown rice, roasted vegetables, chickpeas, avocado, tahini dressing", method: "Arrange warm grains, roasted vegetables and chickpeas in a bowl, then drizzle with a tahini dressing." },
  { name: "Salmon poke bowl", cuisine: "Western", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "1 bowl (350 g)", kcal: 460, protein: 28, carbs: 50, fat: 16, ingredients: "Sushi rice, raw or seared salmon, edamame, cucumber, avocado, soy sauce", method: "Arrange rice, cubed salmon and fresh vegetables in a bowl and dress with soy sauce and sesame oil." },
  { name: "Chicken katsu curry", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (350 g)", kcal: 560, protein: 28, carbs: 70, fat: 18, ingredients: "Chicken cutlet, panko crumbs, Japanese curry sauce, rice", method: "Bake or shallow-fry a crumbed chicken cutlet, slice, and serve over rice with a mild Japanese-style curry sauce." },
  { name: "Vegetable okonomiyaki", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 piece", kcal: 320, protein: 11, carbs: 38, fat: 13, ingredients: "Cabbage, flour, egg, spring onion, okonomiyaki sauce", method: "Mix shredded cabbage into a light batter with egg, pan-fry into a thick pancake and top with sauce." },
  { name: "Chicken banh mi", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 sandwich", kcal: 420, protein: 24, carbs: 48, fat: 14, ingredients: "Baguette, chicken, pickled carrot and radish, coriander, chilli", method: "Fill a crisp baguette with spiced chicken, tangy pickled vegetables, coriander and chilli." },
  { name: "Chicken pho", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (400 ml)", kcal: 420, protein: 26, carbs: 55, fat: 9, ingredients: "Rice noodles, chicken, star anise, ginger, herbs, broth", method: "Simmer a fragrant broth with star anise and ginger, then pour over noodles with sliced chicken and fresh herbs." },
  { name: "Chicken bulgogi", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (200 g)", kcal: 340, protein: 28, carbs: 18, fat: 16, ingredients: "Chicken, soy sauce, pear, garlic, sesame oil, spring onion", method: "Marinate thin chicken slices in a sweet soy and pear marinade, then grill or pan-fry until caramelised." },
  { name: "Kimchi fried rice", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 400, protein: 12, carbs: 55, fat: 14, ingredients: "Rice, kimchi, egg, spring onion, sesame oil", method: "Stir-fry chopped kimchi until fragrant, add cold rice and toss well, then top with a fried egg." },
  { name: "Japchae", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 350, protein: 7, carbs: 58, fat: 10, ingredients: "Sweet potato noodles, carrot, spinach, mushroom, soy sauce, sesame oil", method: "Stir-fry vegetables separately, then toss everything with boiled glass noodles in a soy-sesame dressing." },
  { name: "Congee", cuisine: "Asian", diet: "vegan", meals: ["breakfast", "detox"], serving: "1 bowl (300 ml)", kcal: 180, protein: 4, carbs: 36, fat: 2, ingredients: "Rice, water or stock, ginger, spring onion", method: "Simmer rice in plenty of water or stock for a long time until it breaks down into a soft, soothing porridge." },
  { name: "Egg fried rice", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 380, protein: 12, carbs: 54, fat: 12, ingredients: "Rice, egg, spring onion, soy sauce, oil", method: "Scramble the egg first, then stir-fry with cold rice, spring onion and a dash of soy sauce." },
  { name: "Chilaquiles", cuisine: "Mexican", diet: "eggetarian", meals: ["breakfast"], serving: "1 plate (250 g)", kcal: 380, protein: 14, carbs: 40, fat: 18, ingredients: "Tortilla chips, salsa, egg, cheese, coriander", method: "Simmer tortilla chips briefly in salsa until just softened, top with a fried egg, cheese and coriander." },
  { name: "Chicken enchiladas", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "2 pieces", kcal: 460, protein: 28, carbs: 38, fat: 22, ingredients: "Tortilla, chicken, salsa, cheese, onion", method: "Roll shredded spiced chicken in tortillas, cover with salsa and cheese, and bake until bubbling." },
  { name: "Vegetable fajitas", cuisine: "Mexican", diet: "vegan", meals: ["lunch", "dinner"], serving: "2 fajitas", kcal: 380, protein: 9, carbs: 56, fat: 13, ingredients: "Tortilla, capsicum, onion, beans, fajita spice, oil", method: "Sauté sliced peppers and onion with fajita spices until charred at the edges, and wrap in warm tortillas." },
  { name: "Fish ceviche", cuisine: "Mexican", diet: "pescatarian", meals: ["salad", "snack", "detox"], serving: "1 bowl (150 g)", kcal: 160, protein: 20, carbs: 8, fat: 5, ingredients: "Firm white fish, lime juice, onion, tomato, coriander, chilli", method: "'Cook' diced raw fish in fresh lime juice until opaque, then toss with onion, tomato and coriander." },
  { name: "Moroccan chickpea tagine", cuisine: "Mediterranean", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 280, protein: 10, carbs: 42, fat: 8, ingredients: "Chickpeas, apricot, tomato, cinnamon, cumin, olive oil", method: "Simmer chickpeas with tomato, dried apricot and warm spices until thick and fragrant." },
  { name: "Couscous salad", cuisine: "Mediterranean", diet: "vegan", meals: ["salad", "lunch"], serving: "1 bowl (200 g)", kcal: 260, protein: 7, carbs: 44, fat: 6, ingredients: "Couscous, cucumber, tomato, mint, lemon, olive oil", method: "Fluff steamed couscous and toss with chopped herbs, vegetables and a lemon-olive oil dressing." },
  { name: "Red lentil soup", cuisine: "Mediterranean", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 210, protein: 12, carbs: 32, fat: 4, ingredients: "Red lentils, carrot, cumin, lemon, olive oil", method: "Simmer red lentils with carrot and cumin until soft, blend lightly and finish with lemon juice." },
  { name: "Borscht", cuisine: "Western", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 140, protein: 4, carbs: 22, fat: 4, ingredients: "Beetroot, cabbage, carrot, onion, dill, vinegar", method: "Simmer beetroot and vegetables together until tender, and serve warm or chilled with a splash of vinegar." },
  { name: "Stuffed bell peppers", cuisine: "Western", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "2 halves", kcal: 300, protein: 12, carbs: 34, fat: 12, ingredients: "Bell peppers, rice, cheese, tomato, herbs", method: "Fill halved peppers with a rice and cheese mixture and bake until the peppers are tender." },
  { name: "Vegetable frittata", cuisine: "Western", diet: "eggetarian", meals: ["breakfast"], serving: "1 wedge", kcal: 220, protein: 14, carbs: 6, fat: 15, ingredients: "Eggs, spinach, capsicum, onion, cheese", method: "Whisk eggs with sautéed vegetables and cheese, pour into a pan and cook gently until just set, then finish under a grill." },
];

// Batch 3: more South Indian variety, North Indian breakfast/parathas,
// street food, soups, more global (Greek, Spanish, Thai, French) and
// high-protein/fitness options. No beef.
const BATCH_3: Dish[] = [
  { name: "Vegetable poriyal", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (120 g)", kcal: 110, protein: 3, carbs: 10, fat: 6, ingredients: "Mixed vegetables, coconut, mustard seeds, curry leaves, oil", method: "Sauté chopped vegetables with a mustard seed tempering until just tender, then finish with grated coconut." },
  { name: "Cabbage poriyal", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (120 g)", kcal: 100, protein: 3, carbs: 10, fat: 5, ingredients: "Cabbage, coconut, mustard seeds, curry leaves, oil", method: "Stir-fry shredded cabbage with a light tempering until soft, then toss with fresh coconut." },
  { name: "Beans poriyal", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (120 g)", kcal: 110, protein: 3, carbs: 11, fat: 6, ingredients: "French beans, coconut, mustard seeds, curry leaves, oil", method: "Sauté chopped beans with a mustard tempering until tender-crisp, then finish with coconut." },
  { name: "Vatha kuzhambu", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 150, protein: 4, carbs: 18, fat: 7, ingredients: "Tamarind, sun-dried vegetables, sambar powder, mustard seeds, oil", method: "Simmer a tangy tamarind gravy with sun-dried vegetables and spices until the oil separates." },
  { name: "Mixed vegetable kootu", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 140, protein: 6, carbs: 16, fat: 5, ingredients: "Mixed vegetables, moong dal, coconut, cumin, oil", method: "Cook vegetables and dal together until soft, then blend in a coconut-cumin paste." },
  { name: "Ven pongal", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast"], serving: "1 bowl (200 g)", kcal: 280, protein: 7, carbs: 40, fat: 10, ingredients: "Rice, moong dal, ghee, pepper, cumin, cashew", method: "Cook rice and moong dal together until soft and mushy, then temper generously with ghee, pepper and cashew." },
  { name: "Adai", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 medium", kcal: 200, protein: 8, carbs: 30, fat: 5, ingredients: "Mixed lentils, rice, red chilli, ginger, oil", method: "Grind soaked lentils and rice into a coarse batter, spread thick on a tawa and cook until crisp at the edges." },
  { name: "Paruppu vada", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "3 pieces", kcal: 210, protein: 7, carbs: 22, fat: 10, ingredients: "Chana dal, onion, ginger, curry leaves, oil", method: "Grind soaked chana dal coarsely with spices, shape into patties and deep-fry until golden." },
  { name: "Rasam vada", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 220, protein: 7, carbs: 28, fat: 9, ingredients: "Urad dal vada, rasam", method: "Soak crisp lentil vadas in hot rasam just before serving so they soften slightly while staying textured." },
  { name: "Curd semiya", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "1 bowl (200 g)", kcal: 220, protein: 6, carbs: 32, fat: 7, ingredients: "Vermicelli, curd, mustard seeds, curry leaves, pomegranate", method: "Cook vermicelli until soft, cool, then mix with whisked curd and a light tempering." },
  { name: "Idiyappam", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 cup", kcal: 190, protein: 4, carbs: 40, fat: 1, ingredients: "Rice flour, water, salt", method: "Press rice flour dough through a press into thin noodle strands and steam until translucent." },
  { name: "Neer dosa", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 pieces", kcal: 180, protein: 3, carbs: 34, fat: 3, ingredients: "Rice flour, water, salt", method: "Pour a thin rice batter onto a hot tawa and swirl quickly so it spreads into a lacy, soft dosa." },
  { name: "Aloo puri", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 puri + sabzi", kcal: 380, protein: 7, carbs: 50, fat: 16, ingredients: "Refined flour, potato, cumin, oil", method: "Deep-fry small dough discs until puffed, and serve with a lightly spiced potato curry." },
  { name: "Chole puri", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "2 puri + chole", kcal: 460, protein: 12, carbs: 58, fat: 18, ingredients: "Chickpeas, onion, tomato, chole masala, refined flour, oil", method: "Simmer chickpeas in a tangy masala and serve with hot, puffed fried bread." },
  { name: "Methi paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 piece", kcal: 200, protein: 5, carbs: 28, fat: 8, ingredients: "Wheat flour, fenugreek leaves, spices, oil", method: "Knead chopped fenugreek leaves and spices into the dough, roll and cook on a tawa with a little oil." },
  { name: "Mooli paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 piece", kcal: 220, protein: 5, carbs: 30, fat: 9, ingredients: "Wheat flour, grated radish, spices, oil", method: "Stuff a squeezed radish and spice filling into dough, roll gently and cook until golden." },
  { name: "Gobi paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 piece", kcal: 220, protein: 5, carbs: 30, fat: 9, ingredients: "Wheat flour, grated cauliflower, spices, oil", method: "Stuff a spiced cauliflower filling into dough, roll carefully and cook with a little oil until crisp." },
  { name: "Paneer paratha", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast"], serving: "1 piece", kcal: 260, protein: 9, carbs: 30, fat: 11, ingredients: "Wheat flour, crumbled paneer, spices, oil", method: "Stuff a spiced paneer filling into dough, roll gently and cook on a tawa until golden on both sides." },
  { name: "Palak paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 piece", kcal: 190, protein: 5, carbs: 28, fat: 6, ingredients: "Wheat flour, spinach puree, spices, oil", method: "Knead spinach puree into the dough, roll thin and cook on a hot tawa with a little oil." },
  { name: "Aloo tikki", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "2 pieces", kcal: 220, protein: 4, carbs: 32, fat: 9, ingredients: "Potato, peas, spices, oil", method: "Shape a spiced mashed potato mixture into patties and shallow-fry until crisp and golden." },
  { name: "Dabeli", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "1 piece", kcal: 280, protein: 5, carbs: 46, fat: 8, ingredients: "Pav, spiced potato, tamarind chutney, peanuts, pomegranate", method: "Fill a toasted pav with spiced mashed potato, chutneys, crushed peanuts and pomegranate." },
  { name: "Paneer kathi roll", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "snack"], serving: "1 roll", kcal: 380, protein: 14, carbs: 40, fat: 18, ingredients: "Paratha, paneer, onion, capsicum, mint chutney", method: "Stir-fry spiced paneer and vegetables, roll tightly inside a warm paratha with chutney." },
  { name: "Chicken frankie", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner", "snack"], serving: "1 roll", kcal: 400, protein: 22, carbs: 38, fat: 17, ingredients: "Paratha, chicken, onion, egg, mint chutney", method: "Cook spiced chicken, roll it inside a paratha coated with beaten egg, along with onion and chutney." },
  { name: "Vegetable cutlet", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "2 pieces", kcal: 220, protein: 5, carbs: 28, fat: 9, ingredients: "Mixed vegetables, potato, breadcrumbs, spices, oil", method: "Shape a mashed vegetable mixture into patties, coat in crumbs and shallow-fry until crisp." },
  { name: "Corn chaat", cuisine: "Indian", diet: "vegan", meals: ["salad", "snack", "detox"], serving: "1 bowl (150 g)", kcal: 150, protein: 4, carbs: 26, fat: 4, ingredients: "Boiled corn, onion, tomato, lemon, chaat masala", method: "Toss boiled corn kernels with chopped vegetables, lemon juice and chaat masala." },
  { name: "Papdi chaat", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 plate", kcal: 320, protein: 7, carbs: 40, fat: 15, ingredients: "Papdi, potato, curd, tamarind and mint chutney, sev", method: "Layer crisp papdi with spiced potato, whisked curd, chutneys and a scatter of sev." },
  { name: "Sweet corn soup", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 140, protein: 4, carbs: 24, fat: 3, ingredients: "Sweet corn, carrot, spring onion, cornflour, vegetable stock", method: "Simmer creamed and whole corn kernels in a light vegetable stock, thickened slightly with cornflour." },
  { name: "Veg Manchow soup", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl (250 ml)", kcal: 160, protein: 4, carbs: 22, fat: 6, ingredients: "Mixed vegetables, garlic, soy sauce, cornflour, fried noodles", method: "Simmer chopped vegetables in a garlicky soy-spiked broth, thickened lightly and topped with crisp fried noodles." },
  { name: "Tomato soup", cuisine: "Western", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 110, protein: 2, carbs: 18, fat: 4, ingredients: "Tomato, onion, garlic, basil, olive oil", method: "Simmer tomatoes with onion and garlic until soft, then blend smooth and finish with basil." },
  { name: "Hot and sour soup", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl (250 ml)", kcal: 130, protein: 4, carbs: 18, fat: 4, ingredients: "Mixed vegetables, vinegar, chilli, cornflour, soy sauce", method: "Simmer vegetables in a tangy, peppery broth thickened lightly with cornflour." },
  { name: "Chicken clear soup", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 110, protein: 12, carbs: 6, fat: 4, ingredients: "Chicken, carrot, celery, garlic, herbs", method: "Simmer chicken with aromatics and vegetables for a light, clean-tasting broth." },
  { name: "Bruschetta", cuisine: "Italian", diet: "vegan", meals: ["snack"], serving: "2 pieces", kcal: 200, protein: 5, carbs: 28, fat: 8, ingredients: "Baguette, tomato, basil, garlic, olive oil", method: "Toast baguette slices, rub with garlic, and top with chopped tomato, basil and olive oil." },
  { name: "Pesto pasta", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 460, protein: 13, carbs: 58, fat: 19, ingredients: "Pasta, basil, pine nuts or cashew, parmesan, olive oil", method: "Blend basil, nuts, parmesan and olive oil into a pesto, then toss through hot cooked pasta." },
  { name: "Gnocchi with tomato sauce", cuisine: "Italian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 380, protein: 8, carbs: 68, fat: 8, ingredients: "Potato gnocchi, tomato sauce, garlic, basil, olive oil", method: "Boil potato gnocchi until they float, then toss in a simple garlicky tomato sauce." },
  { name: "French onion soup", cuisine: "Mediterranean", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 ml)", kcal: 260, protein: 9, carbs: 26, fat: 12, ingredients: "Onion, stock, cheese, bread, butter", method: "Slow-cook onions until deeply caramelised, simmer in stock, and top with toasted bread and melted cheese." },
  { name: "Vegetable quiche", cuisine: "Mediterranean", diet: "eggetarian", meals: ["breakfast", "lunch"], serving: "1 slice", kcal: 320, protein: 12, carbs: 22, fat: 20, ingredients: "Egg, cream, spinach, mushroom, cheese, pastry base", method: "Fill a pastry case with sautéed vegetables and a cream-egg mixture, then bake until just set." },
  { name: "Spanish tortilla", cuisine: "Mediterranean", diet: "eggetarian", meals: ["breakfast", "lunch"], serving: "1 wedge", kcal: 260, protein: 10, carbs: 20, fat: 15, ingredients: "Egg, potato, onion, olive oil", method: "Slow-cook sliced potato and onion in olive oil until soft, mix into beaten egg and set into a thick omelette." },
  { name: "Patatas bravas", cuisine: "Mediterranean", diet: "vegan", meals: ["snack"], serving: "1 bowl (150 g)", kcal: 280, protein: 4, carbs: 34, fat: 14, ingredients: "Potato, tomato, paprika, garlic, olive oil", method: "Fry cubed potatoes until crisp, and serve with a smoky paprika-tomato sauce." },
  { name: "Chicken souvlaki", cuisine: "Mediterranean", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "2 skewers", kcal: 300, protein: 28, carbs: 4, fat: 18, ingredients: "Chicken, lemon, oregano, olive oil", method: "Marinate cubed chicken in lemon, oregano and olive oil, then grill on skewers until charred." },
  { name: "Tzatziki", cuisine: "Mediterranean", diet: "vegetarian", meals: ["snack", "detox"], serving: "3 tbsp", kcal: 60, protein: 3, carbs: 4, fat: 4, ingredients: "Curd or Greek yogurt, cucumber, garlic, dill, olive oil", method: "Mix grated cucumber into thick yogurt with garlic, dill and a little olive oil." },
  { name: "Som tam (green papaya salad)", cuisine: "Asian", diet: "vegan", meals: ["salad"], serving: "1 bowl (150 g)", kcal: 120, protein: 3, carbs: 20, fat: 4, ingredients: "Raw papaya, peanuts, lime, chilli, tomato", method: "Pound shredded raw papaya with chilli, lime and tomato until bruised and well mixed, then toss with peanuts." },
  { name: "Chicken massaman curry", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 380, protein: 24, carbs: 14, fat: 26, ingredients: "Chicken, massaman curry paste, coconut milk, potato, peanuts", method: "Simmer chicken and potato in a rich coconut and spice paste until tender, finishing with crushed peanuts." },
  { name: "Vegetable spring rolls", cuisine: "Asian", diet: "vegan", meals: ["snack"], serving: "4 pieces", kcal: 220, protein: 4, carbs: 28, fat: 10, ingredients: "Spring roll wrapper, cabbage, carrot, glass noodles, oil", method: "Roll a stir-fried vegetable filling tightly in thin wrappers and fry until crisp." },
  { name: "Chicken manchurian (dry)", cuisine: "Asian", diet: "non_vegetarian", meals: ["snack", "lunch", "dinner"], serving: "1 plate (200 g)", kcal: 320, protein: 26, carbs: 18, fat: 15, ingredients: "Chicken, cornflour, soy sauce, garlic, spring onion, oil", method: "Fry battered chicken until crisp, then toss with garlic and spring onion in a soy-based sauce." },
  { name: "Sweet corn chicken soup", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 ml)", kcal: 180, protein: 12, carbs: 22, fat: 5, ingredients: "Chicken, sweet corn, egg, cornflour, spring onion", method: "Simmer shredded chicken and corn in a light broth, swirl in beaten egg and thicken slightly." },
  { name: "Grilled paneer salad", cuisine: "Indian", diet: "vegetarian", meals: ["salad", "lunch"], serving: "1 bowl (200 g)", kcal: 280, protein: 16, carbs: 10, fat: 20, ingredients: "Paneer, mixed greens, cucumber, tomato, olive oil, lemon", method: "Grill lightly spiced paneer cubes and toss with fresh greens and a lemon dressing." },
  { name: "Egg white bhurji", cuisine: "Indian", diet: "eggetarian", meals: ["breakfast"], serving: "3 egg whites", kcal: 120, protein: 15, carbs: 3, fat: 4, ingredients: "Egg whites, onion, tomato, green chilli, turmeric, oil", method: "Sauté onion, tomato and spices, then scramble in whisked egg whites until just set." },
  { name: "Peanut butter protein smoothie", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "1 glass (300 ml)", kcal: 320, protein: 14, carbs: 34, fat: 14, ingredients: "Milk, banana, peanut butter, oats", method: "Blend milk, banana, peanut butter and a spoon of oats until thick and smooth." },
  { name: "Chana and paneer bowl", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "salad"], serving: "1 bowl (250 g)", kcal: 340, protein: 22, carbs: 30, fat: 14, ingredients: "Boiled chickpeas, paneer, cucumber, tomato, lemon, chaat masala", method: "Toss boiled chickpeas and lightly grilled paneer with fresh vegetables and a lemony dressing." },
  { name: "Grilled chicken salad bowl", cuisine: "Western", diet: "non_vegetarian", meals: ["salad", "lunch", "dinner"], serving: "1 bowl (300 g)", kcal: 380, protein: 34, carbs: 16, fat: 18, ingredients: "Grilled chicken, mixed greens, cherry tomato, cucumber, olive oil", method: "Slice grilled chicken over a bed of fresh greens and vegetables, and dress with olive oil and lemon." },
  { name: "Fruit chaat", cuisine: "Indian", diet: "vegan", meals: ["snack", "detox"], serving: "1 bowl (200 g)", kcal: 140, protein: 2, carbs: 34, fat: 1, ingredients: "Mixed seasonal fruit, chaat masala, lemon", method: "Chop a mix of seasonal fruit, toss with a little chaat masala and lemon juice just before serving." },
  { name: "Dates and nut energy balls", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "2 pieces", kcal: 160, protein: 4, carbs: 20, fat: 8, ingredients: "Dates, almonds, walnuts, cocoa powder", method: "Blend dates with nuts and a little cocoa until sticky, then roll into small balls." },
  { name: "Ragi cookies", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 150, protein: 3, carbs: 20, fat: 6, ingredients: "Finger millet flour, jaggery, ghee", method: "Mix finger millet flour with melted jaggery and ghee, shape into small discs and bake until firm." },
  { name: "Ginger tea", cuisine: "Indian", diet: "vegetarian", meals: ["detox", "snack"], serving: "1 cup (150 ml)", kcal: 60, protein: 1, carbs: 9, fat: 2, ingredients: "Tea leaves, ginger, milk, sugar", method: "Simmer water with crushed ginger and tea leaves, then add milk and a little sugar." },
  { name: "Lemon honey water", cuisine: "Indian", diet: "vegan", meals: ["detox"], serving: "1 glass (250 ml)", kcal: 30, protein: 0, carbs: 8, fat: 0, ingredients: "Lemon, honey, warm water", method: "Stir lemon juice and a spoon of honey into warm water and drink first thing in the morning." },
  { name: "Tulsi herbal tea", cuisine: "Indian", diet: "vegan", meals: ["detox"], serving: "1 cup (150 ml)", kcal: 5, protein: 0, carbs: 1, fat: 0, ingredients: "Tulsi (holy basil) leaves, water", method: "Simmer fresh or dried tulsi leaves in water for a few minutes and strain before drinking." },
  { name: "Jal jeera", cuisine: "Indian", diet: "vegan", meals: ["detox"], serving: "1 glass (250 ml)", kcal: 40, protein: 1, carbs: 9, fat: 0, ingredients: "Cumin, mint, tamarind, black salt, water", method: "Blend cumin, mint and tamarind with black salt and water, then strain and serve chilled." },
  { name: "Methi malai matar", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 260, protein: 7, carbs: 14, fat: 19, ingredients: "Fenugreek leaves, green peas, cream, cashew", method: "Simmer fresh fenugreek leaves and peas in a light cashew-cream gravy until tender." },
  { name: "Lauki kofta curry", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "3 kofta with gravy", kcal: 300, protein: 8, carbs: 26, fat: 18, ingredients: "Bottle gourd, gram flour, tomato gravy, cream", method: "Shape a grated bottle gourd and gram flour mixture into balls, fry lightly and simmer in a tomato gravy." },
  { name: "Baingan masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 170, protein: 3, carbs: 14, fat: 11, ingredients: "Aubergine, onion, tomato, ginger-garlic, oil", method: "Fry aubergine pieces lightly, then simmer in an onion-tomato masala until soft." },
  { name: "Karela sabzi", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 katori (120 g)", kcal: 110, protein: 3, carbs: 10, fat: 7, ingredients: "Bitter gourd, onion, spices, oil", method: "Sauté sliced bitter gourd with onion and spices until browned and tender, letting some bitterness mellow." },
  { name: "Turai sabzi", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (120 g)", kcal: 90, protein: 2, carbs: 8, fat: 6, ingredients: "Ridge gourd, tomato, cumin, oil", method: "Cook peeled ridge gourd with tomato and light spices until soft and juicy." },
  { name: "Arbi masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 190, protein: 3, carbs: 22, fat: 10, ingredients: "Colocasia, onion, tomato, carom seeds, oil", method: "Fry boiled colocasia pieces until lightly crisp, then toss with a spiced onion-tomato masala." },
  { name: "Paneer bhurji", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "lunch", "dinner"], serving: "1 katori (150 g)", kcal: 260, protein: 14, carbs: 8, fat: 19, ingredients: "Crumbled paneer, onion, tomato, capsicum, spices, oil", method: "Sauté onion, tomato and capsicum with spices, then fold in crumbled paneer and cook briefly." },
  { name: "Egg paratha", cuisine: "Indian", diet: "eggetarian", meals: ["breakfast"], serving: "1 piece", kcal: 260, protein: 10, carbs: 26, fat: 13, ingredients: "Wheat flour, egg, onion, chilli, oil", method: "Cook a rolled paratha partway, crack an egg over it with chopped onion and chilli, and fold to cook through." },
  { name: "Chicken keema paratha", cuisine: "Indian", diet: "non_vegetarian", meals: ["breakfast", "lunch", "dinner"], serving: "1 piece", kcal: 320, protein: 16, carbs: 30, fat: 15, ingredients: "Wheat flour, spiced chicken mince, onion, oil", method: "Stuff a spiced chicken mince filling into dough, roll gently and cook until golden on both sides." },
  { name: "Chicken malai tikka", cuisine: "Indian", diet: "non_vegetarian", meals: ["snack", "lunch", "dinner"], serving: "6 pieces (150 g)", kcal: 290, protein: 28, carbs: 3, fat: 18, ingredients: "Chicken, cream, cashew paste, mild spices, curd", method: "Marinate chicken in a creamy cashew and curd marinade, then grill gently until just cooked through." },
  { name: "Chicken korma", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 360, protein: 24, carbs: 10, fat: 24, ingredients: "Chicken, curd, cashew, onion, mild whole spices", method: "Simmer chicken in a mild, creamy onion-cashew gravy until tender and fragrant." },
  { name: "Goan prawn curry", cuisine: "Indian", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 260, protein: 18, carbs: 8, fat: 17, ingredients: "Prawns, coconut, tamarind, red chilli, mustard seeds", method: "Simmer prawns briefly in a tangy coconut and tamarind gravy until just cooked through." },
  { name: "Goan fish curry", cuisine: "Indian", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 240, protein: 20, carbs: 6, fat: 15, ingredients: "Fish, coconut, tamarind, red chilli, curry leaves", method: "Simmer fish in a coconut and tamarind gravy flavoured with red chilli and curry leaves." },
  { name: "Chicken xacuti", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 340, protein: 25, carbs: 9, fat: 22, ingredients: "Chicken, roasted coconut, poppy seed, dry red chilli, whole spices", method: "Simmer chicken in a deeply roasted coconut and spice paste until dark and richly flavoured." },
];

function sqlString(value: string): string {
  return "'" + value.replace(/'/g, "''") + "'";
}

function sqlArray(values: string[]): string {
  return "array[" + values.map(sqlString).join(", ") + "]::text[]";
}

function toRow(d: Dish): string {
  return `(${sqlString(d.name)}, ${sqlString(d.cuisine)}, ${sqlString(d.diet)}, ${sqlArray(d.meals)}, ${sqlString(d.serving)}, ${d.kcal}, ${d.protein}, ${d.carbs}, ${d.fat}, ${sqlString(d.ingredients)}, ${sqlString(d.method)})`;
}

const sql = `-- Seed data for the global \`foods\` library, batch 1: the original
-- prototype dishes (docs/build-brief.md section 5), reclassified with a
-- diet tier and meal category. Generated by scripts/seed-foods.ts --
-- do not hand-edit; change the script and regenerate instead.

insert into public.foods (name, cuisine, diet, meal_category, serving, kcal, protein_g, carbs_g, fat_g, ingredients, method)
values
${BATCH_1.map(toRow).join(",\n")};
`;

const outPath = join(process.cwd(), "supabase", "migrations", "20260922050000_seed_foods_batch_1.sql");
writeFileSync(outPath, sql, "utf8");
console.log(`Wrote ${BATCH_1.length} dishes to ${outPath}`);

const sql2 = `-- Seed data for the global \`foods\` library, batch 2: more regional
-- Indian dishes and global mains/bowls/salads. Generated by
-- scripts/seed-foods.ts -- do not hand-edit; change the script and
-- regenerate instead.

insert into public.foods (name, cuisine, diet, meal_category, serving, kcal, protein_g, carbs_g, fat_g, ingredients, method)
values
${BATCH_2.map(toRow).join(",\n")};
`;

const outPath2 = join(process.cwd(), "supabase", "migrations", "20260923000000_seed_foods_batch_2.sql");
writeFileSync(outPath2, sql2, "utf8");
console.log(`Wrote ${BATCH_2.length} dishes to ${outPath2}`);

const sql3 = `-- Seed data for the global \`foods\` library, batch 3: more South
-- Indian variety, North Indian breakfast/parathas, street food, soups,
-- and more global (Greek, Spanish, Thai, French) plus high-protein
-- options. Generated by scripts/seed-foods.ts -- do not hand-edit;
-- change the script and regenerate instead.

insert into public.foods (name, cuisine, diet, meal_category, serving, kcal, protein_g, carbs_g, fat_g, ingredients, method)
values
${BATCH_3.map(toRow).join(",\n")};
`;

const outPath3 = join(process.cwd(), "supabase", "migrations", "20260923010000_seed_foods_batch_3.sql");
writeFileSync(outPath3, sql3, "utf8");
console.log(`Wrote ${BATCH_3.length} dishes to ${outPath3}`);
