/**
 * Converts the food library into a SQL migration for the `foods` table.
 * Per docs/build-brief.md section 5.
 *
 * Run with: npx tsx scripts/seed-foods.ts
 * Writes: supabase/migrations/<timestamp>_seed_foods_batch_1.sql
 *
 * Diet tiers (strictest to least strict): vegan < vegetarian < eggetarian
 * < pescatarian < non_vegetarian. Each dish is tagged with the loosest
 * tier still required to eat it. No beef anywhere in this library --
 * where the original prototype recipe used beef, it's substituted here
 * (see "Chicken burger", ex-"Cheeseburger"; "Spaghetti bolognese" now
 * specifies chicken or mutton mince rather than unspecified "minced meat").
 *
 * meal_category: which meal(s) this dish suits -- detox, breakfast,
 * lunch, snack, dinner, salad. A dish can suit more than one.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

type Diet = "vegan" | "vegetarian" | "eggetarian" | "pescatarian" | "non_vegetarian";
type Meal = "detox" | "breakfast" | "lunch" | "snack" | "dinner" | "salad";

interface Dish {
  name: string;
  cuisine: string;
  diet: Diet;
  meals: Meal[];
  serving: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  ingredients: string;
  method: string;
}

// Batch 1: the original prototype library (reference/prototype.html's RAW
// array), reclassified with diet tier and meal category. Values are
// estimates per typical home serving.
const BATCH_1: Dish[] = [
  { name: "Roti / phulka", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 medium (40 g)", kcal: 100, protein: 3, carbs: 20, fat: 1, ingredients: "Whole wheat flour, water, salt", method: "Knead a soft dough, rest 15 minutes, roll thin and cook on a hot tawa until it puffs. Skip the ghee to keep it light." },
  { name: "Plain paratha", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "lunch", "dinner"], serving: "1 (80 g)", kcal: 200, protein: 5, carbs: 30, fat: 7, ingredients: "Wheat flour, water, oil or ghee, salt", method: "Knead, roll, fold into layers and cook on a tawa with a little oil until golden on both sides." },
  { name: "Aloo paratha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 (120 g)", kcal: 290, protein: 6, carbs: 40, fat: 12, ingredients: "Wheat flour, boiled potato, green chilli, coriander, cumin, salt, oil", method: "Mix mashed potato with spices, stuff into dough, roll gently and cook with a little oil until crisp and golden." },
  { name: "Steamed rice", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 cup cooked (150 g)", kcal: 195, protein: 4, carbs: 43, fat: 0, ingredients: "Rice, water", method: "Rinse the rice, simmer with about twice the water until fluffy, then rest covered for 5 minutes." },
  { name: "Jeera rice", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 cup (150 g)", kcal: 240, protein: 4, carbs: 44, fat: 5, ingredients: "Basmati rice, cumin seeds, ghee, salt", method: "Sizzle cumin in ghee, add rinsed rice and water, and cook until each grain is separate." },
  { name: "Dal tadka", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 180, protein: 9, carbs: 24, fat: 5, ingredients: "Toor or moong dal, turmeric, tomato, garlic, cumin, chilli, ghee", method: "Pressure-cook the dal with turmeric, mash lightly, then pour over a tempering of ghee, cumin, garlic and chilli." },
  { name: "Moong dal khichdi", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 g)", kcal: 260, protein: 10, carbs: 44, fat: 5, ingredients: "Rice, split moong dal, turmeric, ginger, cumin, ghee, salt", method: "Pressure-cook rice and dal with turmeric and salt until soft, then finish with a ghee and cumin tempering." },
  { name: "Rajma masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 210, protein: 10, carbs: 30, fat: 6, ingredients: "Kidney beans, onion, tomato, ginger-garlic, rajma masala, oil", method: "Soak beans overnight and pressure-cook. Simmer in an onion-tomato masala for 15 minutes until thick." },
  { name: "Chana masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 240, protein: 10, carbs: 32, fat: 8, ingredients: "Chickpeas, onion, tomato, ginger-garlic, chana masala, oil", method: "Cook boiled chickpeas in a browned onion-tomato masala for 15 minutes and finish with lemon and coriander." },
  { name: "Palak paneer", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 260, protein: 12, carbs: 9, fat: 19, ingredients: "Spinach, paneer, onion, tomato, garlic, cumin, cream, oil", method: "Blanch and blend the spinach, cook it with a garlic-tomato masala, then fold in paneer cubes." },
  { name: "Paneer butter masala", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (180 g)", kcal: 380, protein: 14, carbs: 12, fat: 30, ingredients: "Paneer, tomato, cashew, butter, cream, kasuri methi, spices", method: "Simmer blended tomato and cashew with spices and butter, then add paneer, cream and crushed kasuri methi." },
  { name: "Butter chicken", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 360, protein: 25, carbs: 9, fat: 24, ingredients: "Chicken, yogurt, tomato puree, butter, cream, garam masala, kasuri methi", method: "Marinate and grill the chicken, simmer it in buttery tomato gravy and finish with a splash of cream." },
  { name: "Chicken curry (home style)", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (200 g)", kcal: 280, protein: 26, carbs: 7, fat: 16, ingredients: "Chicken, onion, tomato, ginger-garlic, turmeric, coriander powder, garam masala, oil", method: "Brown the onions, add spices and tomato, then cook the chicken covered until tender, about 25 minutes." },
  { name: "Egg curry", cuisine: "Indian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "2 eggs with gravy", kcal: 260, protein: 15, carbs: 8, fat: 18, ingredients: "Boiled eggs, onion, tomato, ginger-garlic, spices, oil", method: "Make an onion-tomato masala, simmer with water for 8 minutes, add halved boiled eggs and cook 5 minutes more." },
  { name: "Aloo gobi", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 150, protein: 4, carbs: 18, fat: 7, ingredients: "Potato, cauliflower, cumin, turmeric, tomato, coriander, oil", method: "Sauté cumin and spices, add potato and cauliflower, cover and cook on low heat until tender." },
  { name: "Bhindi masala", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (130 g)", kcal: 120, protein: 3, carbs: 10, fat: 8, ingredients: "Okra, onion, tomato, amchur, cumin, turmeric, oil", method: "Cook dry okra on high heat so it stays crisp, then toss with onion, spices and amchur." },
  { name: "Baingan bharta", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 g)", kcal: 140, protein: 3, carbs: 12, fat: 9, ingredients: "Roasted aubergine, onion, tomato, garlic, green chilli, oil", method: "Roast the aubergine over a flame, peel and mash, then cook with sautéed onion, tomato and spices." },
  { name: "Idli", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 pieces (100 g)", kcal: 130, protein: 4, carbs: 27, fat: 1, ingredients: "Idli rice, urad dal, salt", method: "Ferment the ground rice and dal batter overnight, pour into moulds and steam for 10 to 12 minutes." },
  { name: "Plain dosa", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 medium", kcal: 150, protein: 3, carbs: 25, fat: 4, ingredients: "Rice, urad dal, fenugreek, salt, a little oil", method: "Spread fermented batter thin on a hot tawa, drizzle a little oil and cook until crisp and golden." },
  { name: "Masala dosa", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 with potato filling", kcal: 340, protein: 7, carbs: 48, fat: 13, ingredients: "Dosa batter, potato, onion, mustard seeds, curry leaves, turmeric, oil", method: "Make a soft potato masala with mustard and onion, then roll it inside a crisp dosa." },
  { name: "Sambar", cuisine: "Indian", diet: "vegan", meals: ["breakfast", "lunch"], serving: "1 katori (150 g)", kcal: 90, protein: 4, carbs: 13, fat: 3, ingredients: "Toor dal, mixed vegetables, tamarind, sambar powder, mustard seeds, curry leaves", method: "Cook dal and vegetables with tamarind and sambar powder, then temper with mustard and curry leaves." },
  { name: "Coconut chutney", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 tbsp (30 g)", kcal: 50, protein: 1, carbs: 2, fat: 4, ingredients: "Fresh coconut, roasted chana, green chilli, ginger, salt, curry leaves", method: "Grind everything with a little water and top with a mustard and curry leaf tempering." },
  { name: "Rasam", cuisine: "Indian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 katori (150 ml)", kcal: 45, protein: 2, carbs: 7, fat: 1, ingredients: "Tomato, tamarind, rasam powder, garlic, pepper, cumin, mustard, curry leaves", method: "Simmer tomato, tamarind and spices, then finish with a quick tempering and coriander." },
  { name: "Upma", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 bowl (200 g)", kcal: 230, protein: 6, carbs: 34, fat: 8, ingredients: "Semolina, onion, green chilli, mustard seeds, curry leaves, peanuts, oil", method: "Roast the semolina, temper the spices, add water and stir the semolina in until fluffy." },
  { name: "Poha", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "1 plate (200 g)", kcal: 250, protein: 5, carbs: 44, fat: 6, ingredients: "Flattened rice, onion, potato, peanuts, turmeric, mustard seeds, lemon", method: "Rinse the poha, sauté onion and spices, fold in the poha and finish with lemon and coriander." },
  { name: "Vegetable pulao", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 cup (200 g)", kcal: 280, protein: 6, carbs: 48, fat: 7, ingredients: "Basmati rice, mixed vegetables, whole spices, ghee, salt", method: "Sauté whole spices and vegetables in ghee, add rice and water, and cook until fluffy." },
  { name: "Chicken biryani", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 520, protein: 27, carbs: 62, fat: 17, ingredients: "Basmati, chicken, yogurt, fried onion, biryani masala, mint, saffron, ghee", method: "Marinate chicken in yogurt and spices, layer with par-cooked rice, mint and fried onion, and steam on low heat." },
  { name: "Veg biryani", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 450, protein: 10, carbs: 68, fat: 14, ingredients: "Basmati, mixed vegetables, yogurt, fried onion, biryani masala, mint, ghee", method: "Layer spiced vegetables with par-cooked rice and mint, then seal and steam for 20 minutes." },
  { name: "Dhokla", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "4 pieces (120 g)", kcal: 160, protein: 6, carbs: 26, fat: 4, ingredients: "Gram flour, yogurt, ginger-chilli paste, fruit salt, mustard seeds", method: "Whisk a batter, add fruit salt and steam for 15 minutes, then pour over a mustard tempering." },
  { name: "Thepla", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "2 pieces", kcal: 200, protein: 6, carbs: 28, fat: 7, ingredients: "Wheat flour, fenugreek leaves, yogurt, turmeric, sesame, oil", method: "Knead everything into a dough, roll thin and cook with a little oil until speckled." },
  { name: "Pav bhaji", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "snack"], serving: "2 pav + 1 cup bhaji", kcal: 490, protein: 11, carbs: 70, fat: 18, ingredients: "Mixed vegetables, potato, tomato, butter, pav bhaji masala, pav", method: "Boil and mash the vegetables, cook in butter with masala until thick, then toast the pav in butter." },
  { name: "Vada pav", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1", kcal: 290, protein: 6, carbs: 41, fat: 11, ingredients: "Potato, gram flour, garlic chutney, pav, green chilli", method: "Coat spiced potato balls in gram-flour batter, fry until golden and tuck into a pav with chutney." },
  { name: "Misal pav", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "1 plate", kcal: 420, protein: 14, carbs: 56, fat: 15, ingredients: "Sprouted moth beans, onion, tomato, misal masala, farsan, pav", method: "Cook sprouts in a spicy masala, ladle into a plate, top with farsan and onion, and serve with pav." },
  { name: "Samosa", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 fried (60 g)", kcal: 260, protein: 4, carbs: 26, fat: 15, ingredients: "Flour, potato, peas, cumin, coriander, amchur, oil", method: "Fill a crisp dough cone with spiced potato and peas and fry slowly until golden. Baking cuts the calories." },
  { name: "Onion pakora", cuisine: "Indian", diet: "vegan", meals: ["snack"], serving: "5 pieces (75 g)", kcal: 230, protein: 6, carbs: 20, fat: 14, ingredients: "Onion, gram flour, ajwain, chilli, salt, oil", method: "Mix sliced onion into a thick gram-flour batter and fry in small portions until crisp." },
  { name: "Sabudana khichdi", cuisine: "Indian", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 plate (200 g)", kcal: 350, protein: 4, carbs: 55, fat: 13, ingredients: "Soaked sago, potato, peanuts, cumin, green chilli, ghee", method: "Soak sabudana until soft, then toss in ghee with cumin, potato and crushed peanuts. A traditional Indian fasting-day dish." },
  { name: "Besan chilla", cuisine: "Indian", diet: "vegan", meals: ["breakfast"], serving: "2 pieces", kcal: 230, protein: 11, carbs: 27, fat: 9, ingredients: "Gram flour, onion, tomato, green chilli, ajwain, coriander, oil", method: "Whisk a thin batter with chopped vegetables and cook on a lightly oiled tawa until golden." },
  { name: "Sprouts chaat", cuisine: "Indian", diet: "vegan", meals: ["snack", "salad", "detox"], serving: "1 bowl (150 g)", kcal: 130, protein: 9, carbs: 20, fat: 1, ingredients: "Moong sprouts, onion, tomato, cucumber, chaat masala, lemon", method: "Steam the sprouts briefly, toss with chopped vegetables, chaat masala and lemon." },
  { name: "Tandoori chicken", cuisine: "Indian", diet: "non_vegetarian", meals: ["lunch", "dinner", "snack"], serving: "2 pieces (200 g)", kcal: 290, protein: 36, carbs: 5, fat: 14, ingredients: "Chicken, hung curd, tandoori masala, ginger-garlic, lemon, mustard oil", method: "Marinate in spiced curd for at least 4 hours, then grill or roast until charred at the edges." },
  { name: "Egg bhurji", cuisine: "Indian", diet: "eggetarian", meals: ["breakfast"], serving: "2 eggs", kcal: 220, protein: 13, carbs: 4, fat: 16, ingredients: "Eggs, onion, tomato, green chilli, turmeric, coriander, oil", method: "Sauté onion, tomato and spices, pour in beaten eggs and scramble softly." },
  { name: "Curd rice", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 g)", kcal: 260, protein: 8, carbs: 38, fat: 8, ingredients: "Cooked rice, curd, mustard seeds, curry leaves, ginger, green chilli", method: "Mash warm rice with curd and salt, then top with a mustard and curry leaf tempering." },
  { name: "Dahi / curd", cuisine: "Indian", diet: "vegetarian", meals: ["snack", "detox"], serving: "1 katori (100 g)", kcal: 60, protein: 3, carbs: 5, fat: 3, ingredients: "Milk, a spoon of curd as starter", method: "Warm milk to lukewarm, stir in a spoon of curd and leave in a warm place for 6 to 8 hours." },
  { name: "Cucumber raita", cuisine: "Indian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 katori (100 g)", kcal: 50, protein: 3, carbs: 5, fat: 2, ingredients: "Curd, cucumber, roasted cumin, salt, mint", method: "Whisk the curd, stir in grated cucumber and season with roasted cumin and salt." },
  { name: "Masala chai", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 cup (150 ml)", kcal: 90, protein: 2, carbs: 13, fat: 3, ingredients: "Tea leaves, milk, water, sugar, ginger, cardamom", method: "Simmer water with tea, ginger and cardamom, add milk and sugar and bring to a boil." },
  { name: "Sweet lassi", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 glass (250 ml)", kcal: 220, protein: 7, carbs: 34, fat: 6, ingredients: "Curd, sugar, cold water, cardamom", method: "Blend curd with water, sugar and cardamom until frothy and serve cold." },
  { name: "Gulab jamun", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "2 pieces", kcal: 300, protein: 4, carbs: 45, fat: 12, ingredients: "Khoya or milk powder, flour, sugar, cardamom, ghee", method: "Shape soft dough balls, fry gently on low heat and soak in warm cardamom sugar syrup." },
  { name: "Kheer", cuisine: "Indian", diet: "vegetarian", meals: ["snack"], serving: "1 katori (150 g)", kcal: 220, protein: 6, carbs: 32, fat: 8, ingredients: "Milk, rice, sugar, cardamom, nuts", method: "Simmer rice in milk, stirring often, until creamy, then sweeten and flavour with cardamom." },
  { name: "Margherita pizza", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "2 slices", kcal: 540, protein: 22, carbs: 66, fat: 20, ingredients: "Pizza dough, tomato sauce, mozzarella, basil, olive oil", method: "Stretch the dough, top with sauce and mozzarella and bake very hot until the crust blisters." },
  { name: "Spaghetti bolognese", cuisine: "Italian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 520, protein: 26, carbs: 65, fat: 16, ingredients: "Spaghetti, chicken or mutton mince, onion, carrot, tomato, garlic, olive oil", method: "Simmer the mince with onion, carrot and tomato for 30 minutes and toss through cooked spaghetti." },
  { name: "Pasta arrabbiata", cuisine: "Italian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 420, protein: 13, carbs: 72, fat: 9, ingredients: "Penne, tomato, garlic, dried chilli, olive oil, parsley", method: "Cook garlic and chilli in olive oil, add tomato and simmer, then toss with al dente penne." },
  { name: "Vegetable lasagna", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 piece (250 g)", kcal: 400, protein: 19, carbs: 35, fat: 20, ingredients: "Lasagna sheets, spinach, ricotta, tomato sauce, mozzarella", method: "Layer sheets with sauce, spinach and ricotta, cover with mozzarella and bake for 35 minutes." },
  { name: "Mushroom risotto", cuisine: "Italian", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 380, protein: 9, carbs: 56, fat: 12, ingredients: "Arborio rice, mushrooms, onion, stock, parmesan, butter", method: "Toast the rice, add hot stock a ladle at a time, stirring, and finish with butter and parmesan." },
  { name: "Caprese salad", cuisine: "Italian", diet: "vegetarian", meals: ["salad", "lunch"], serving: "1 plate (150 g)", kcal: 220, protein: 13, carbs: 5, fat: 17, ingredients: "Tomato, mozzarella, basil, olive oil, salt", method: "Layer sliced tomato and mozzarella with basil and dress with olive oil and salt." },
  { name: "Minestrone soup", cuisine: "Italian", diet: "vegan", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 130, protein: 5, carbs: 20, fat: 3, ingredients: "Beans, small pasta, carrot, celery, tomato, onion, olive oil", method: "Simmer the vegetables and beans in stock, add small pasta and cook until tender." },
  { name: "Chicken burrito", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 burrito", kcal: 600, protein: 30, carbs: 66, fat: 24, ingredients: "Flour tortilla, chicken, rice, beans, salsa, cheese", method: "Fill a warm tortilla with spiced chicken, rice, beans, salsa and cheese, then roll tightly." },
  { name: "Bean burrito bowl", cuisine: "Mexican", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 480, protein: 18, carbs: 70, fat: 14, ingredients: "Rice, black beans, corn, salsa, avocado, lime", method: "Layer warm rice and beans with corn, salsa and avocado and finish with lime." },
  { name: "Chicken tacos", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "2 tacos", kcal: 340, protein: 22, carbs: 32, fat: 13, ingredients: "Corn tortillas, chicken, onion, coriander, lime, salsa", method: "Cook spiced chicken, pile it into warm tortillas and top with onion, coriander and lime." },
  { name: "Veg tacos", cuisine: "Mexican", diet: "vegan", meals: ["lunch", "dinner"], serving: "2 tacos", kcal: 320, protein: 10, carbs: 42, fat: 13, ingredients: "Corn tortillas, beans, peppers, onion, avocado, salsa", method: "Sauté peppers and onion with spices, fill tortillas with beans and vegetables and top with salsa." },
  { name: "Chicken quesadilla", cuisine: "Mexican", diet: "non_vegetarian", meals: ["lunch", "dinner", "snack"], serving: "1 quesadilla", kcal: 550, protein: 30, carbs: 40, fat: 28, ingredients: "Tortilla, chicken, cheese, peppers, onion", method: "Fill a tortilla with chicken and cheese and toast in a pan until crisp and melted." },
  { name: "Veg fried rice", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 350, protein: 8, carbs: 58, fat: 9, ingredients: "Rice, carrot, beans, spring onion, soy sauce, garlic, oil", method: "Stir-fry the vegetables and garlic on high heat, add cold cooked rice and soy sauce and toss well." },
  { name: "Chicken fried rice", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 420, protein: 20, carbs: 58, fat: 12, ingredients: "Rice, chicken, egg, spring onion, soy sauce, garlic, oil", method: "Scramble the egg, stir-fry the chicken and garlic, then add cold rice and soy sauce." },
  { name: "Veg hakka noodles", cuisine: "Asian", diet: "vegan", meals: ["lunch", "dinner"], serving: "1 plate (250 g)", kcal: 380, protein: 9, carbs: 62, fat: 10, ingredients: "Noodles, cabbage, carrot, capsicum, soy sauce, vinegar, oil", method: "Boil the noodles, then stir-fry with vegetables and sauces on the highest heat." },
  { name: "Steamed veg momos", cuisine: "Asian", diet: "vegan", meals: ["snack"], serving: "6 pieces", kcal: 210, protein: 7, carbs: 38, fat: 3, ingredients: "Flour, cabbage, carrot, ginger, garlic, spring onion", method: "Fill thin dough with finely chopped seasoned vegetables and steam for 10 minutes." },
  { name: "Steamed chicken momos", cuisine: "Asian", diet: "non_vegetarian", meals: ["snack"], serving: "6 pieces", kcal: 250, protein: 15, carbs: 30, fat: 7, ingredients: "Flour, minced chicken, ginger, garlic, spring onion", method: "Fill dough with seasoned chicken mince and steam for 10 to 12 minutes." },
  { name: "Cucumber avocado sushi roll", cuisine: "Asian", diet: "vegan", meals: ["lunch", "snack"], serving: "8 pieces", kcal: 270, protein: 6, carbs: 50, fat: 5, ingredients: "Sushi rice, nori, cucumber, avocado, rice vinegar", method: "Spread seasoned rice on nori, add cucumber and avocado, roll tightly and slice." },
  { name: "Miso soup", cuisine: "Asian", diet: "pescatarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (240 ml)", kcal: 60, protein: 4, carbs: 6, fat: 2, ingredients: "Dashi (fish stock), miso paste, tofu, spring onion, wakame", method: "Warm the dashi, whisk in miso off the boil and add tofu and spring onion. Use a kombu-only dashi to make it vegan." },
  { name: "Chicken ramen", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 480, protein: 24, carbs: 60, fat: 16, ingredients: "Noodles, chicken, broth, egg, spring onion, soy sauce", method: "Simmer a savoury broth, cook noodles separately and top with chicken, egg and spring onion." },
  { name: "Thai green curry (chicken)", cuisine: "Asian", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 bowl (250 g)", kcal: 320, protein: 22, carbs: 10, fat: 22, ingredients: "Chicken, green curry paste, coconut milk, aubergine, Thai basil, fish sauce", method: "Fry the paste, add coconut milk and chicken and simmer until cooked, finishing with Thai basil." },
  { name: "Pad Thai (tofu)", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 plate (300 g)", kcal: 550, protein: 20, carbs: 72, fat: 20, ingredients: "Rice noodles, tofu, egg, bean sprouts, peanuts, tamarind, lime", method: "Stir-fry noodles with tofu, egg and tamarind sauce, then top with sprouts, peanuts and lime." },
  { name: "Tom yum soup (prawn)", cuisine: "Asian", diet: "pescatarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl", kcal: 90, protein: 10, carbs: 6, fat: 3, ingredients: "Prawns, lemongrass, galangal, lime leaf, mushrooms, chilli, lime", method: "Simmer the aromatics in stock, add mushrooms and prawns and finish with lime juice." },
  { name: "Veg bibimbap", cuisine: "Asian", diet: "eggetarian", meals: ["lunch", "dinner"], serving: "1 bowl", kcal: 500, protein: 16, carbs: 82, fat: 12, ingredients: "Rice, spinach, carrot, mushrooms, egg, gochujang, sesame oil", method: "Top warm rice with seasoned vegetables and a fried egg, and mix in gochujang before eating." },
  { name: "Hummus with pita", cuisine: "Mediterranean", diet: "vegan", meals: ["snack", "detox"], serving: "3 tbsp + 1 pita", kcal: 280, protein: 9, carbs: 38, fat: 10, ingredients: "Chickpeas, tahini, lemon, garlic, olive oil, pita", method: "Blend chickpeas with tahini, lemon, garlic and olive oil until smooth and serve with warm pita." },
  { name: "Falafel", cuisine: "Mediterranean", diet: "vegan", meals: ["lunch", "dinner", "snack"], serving: "4 pieces (100 g)", kcal: 300, protein: 12, carbs: 28, fat: 16, ingredients: "Chickpeas, parsley, coriander, onion, garlic, cumin", method: "Blend soaked chickpeas with herbs and spices, shape into balls and bake or fry until golden." },
  { name: "Greek salad", cuisine: "Mediterranean", diet: "vegetarian", meals: ["salad", "lunch"], serving: "1 bowl (200 g)", kcal: 190, protein: 6, carbs: 10, fat: 14, ingredients: "Cucumber, tomato, olives, feta, red onion, olive oil", method: "Chop the vegetables, add olives and feta and dress with olive oil and oregano." },
  { name: "Chicken shawarma wrap", cuisine: "Mediterranean", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 wrap", kcal: 480, protein: 30, carbs: 42, fat: 20, ingredients: "Chicken, yogurt, shawarma spices, pita, garlic sauce, pickles", method: "Marinate and roast the chicken, slice thinly and wrap in pita with garlic sauce and pickles." },
  { name: "Shakshuka", cuisine: "Mediterranean", diet: "eggetarian", meals: ["breakfast"], serving: "2 eggs", kcal: 250, protein: 15, carbs: 13, fat: 16, ingredients: "Eggs, tomato, capsicum, onion, garlic, cumin, paprika", method: "Simmer a spiced tomato and pepper sauce, make wells, crack in eggs and cover until set." },
  { name: "Tabbouleh", cuisine: "Mediterranean", diet: "vegan", meals: ["salad", "lunch"], serving: "1 cup (150 g)", kcal: 150, protein: 3, carbs: 17, fat: 8, ingredients: "Parsley, bulgur, tomato, mint, lemon, olive oil", method: "Soak bulgur, then mix with plenty of chopped parsley, tomato, mint, lemon and olive oil." },
  { name: "Grilled chicken breast", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "150 g", kcal: 250, protein: 46, carbs: 0, fat: 6, ingredients: "Chicken breast, olive oil, garlic, lemon, pepper", method: "Marinate briefly and grill 5 to 6 minutes a side until cooked through, then rest before slicing." },
  { name: "Veg grilled sandwich", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "lunch", "snack"], serving: "1 (2 slices)", kcal: 280, protein: 9, carbs: 38, fat: 10, ingredients: "Bread, cucumber, tomato, cheese, green chutney, butter", method: "Layer vegetables, cheese and chutney between slices and toast until golden." },
  { name: "Plain omelette", cuisine: "Western", diet: "eggetarian", meals: ["breakfast"], serving: "2 eggs", kcal: 200, protein: 13, carbs: 1, fat: 16, ingredients: "Eggs, butter, salt, pepper, herbs", method: "Whisk the eggs, pour into a buttered pan, fold when nearly set and slide onto a plate." },
  { name: "Avocado toast", cuisine: "Western", diet: "vegan", meals: ["breakfast"], serving: "1 slice", kcal: 240, protein: 6, carbs: 26, fat: 13, ingredients: "Sourdough, avocado, lemon, chilli flakes, salt", method: "Toast the bread, mash the avocado with lemon and salt and spread it on top." },
  { name: "Chicken Caesar salad", cuisine: "Western", diet: "non_vegetarian", meals: ["salad", "lunch"], serving: "1 bowl", kcal: 420, protein: 30, carbs: 16, fat: 26, ingredients: "Romaine, grilled chicken, parmesan, croutons, Caesar dressing", method: "Toss the lettuce with dressing, top with sliced chicken, parmesan and croutons." },
  { name: "Pancakes with syrup", cuisine: "Western", diet: "eggetarian", meals: ["breakfast"], serving: "3 pancakes", kcal: 450, protein: 8, carbs: 80, fat: 9, ingredients: "Flour, milk, egg, baking powder, sugar, maple syrup", method: "Whisk a thick batter, cook small rounds until bubbles appear, flip and serve with syrup." },
  { name: "Chicken burger", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner"], serving: "1 burger", kcal: 480, protein: 28, carbs: 40, fat: 22, ingredients: "Bun, chicken patty, cheese, lettuce, tomato, onion", method: "Grill the patty, melt cheese on top and stack in a toasted bun with the vegetables." },
  { name: "French fries", cuisine: "Western", diet: "vegan", meals: ["snack"], serving: "1 medium (115 g)", kcal: 365, protein: 4, carbs: 48, fat: 17, ingredients: "Potatoes, oil, salt", method: "Cut, soak and dry the potatoes, then fry until golden. Oven-baking cuts the fat." },
  { name: "Overnight oats", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 jar", kcal: 320, protein: 12, carbs: 46, fat: 10, ingredients: "Rolled oats, milk, yogurt, chia seeds, fruit", method: "Mix everything in a jar and chill overnight; top with fresh fruit in the morning." },
  { name: "Greek yogurt with berries", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "snack", "detox"], serving: "1 bowl (200 g)", kcal: 180, protein: 17, carbs: 18, fat: 4, ingredients: "Greek yogurt, berries, honey", method: "Spoon the yogurt into a bowl and top with berries and a little honey." },
  { name: "Mac and cheese", cuisine: "Western", diet: "vegetarian", meals: ["lunch", "dinner"], serving: "1 cup (200 g)", kcal: 380, protein: 14, carbs: 40, fat: 18, ingredients: "Macaroni, milk, cheddar, butter, flour", method: "Make a cheese sauce with butter, flour, milk and cheddar and fold through the cooked macaroni." },
  { name: "Grilled salmon", cuisine: "Western", diet: "pescatarian", meals: ["lunch", "dinner"], serving: "150 g", kcal: 310, protein: 33, carbs: 0, fat: 19, ingredients: "Salmon fillet, lemon, garlic, olive oil, dill", method: "Season the fillet and grill or pan-sear about 4 minutes a side until it flakes." },
  { name: "Banana peanut smoothie", cuisine: "Western", diet: "vegetarian", meals: ["breakfast", "snack", "detox"], serving: "1 glass (300 ml)", kcal: 320, protein: 10, carbs: 48, fat: 10, ingredients: "Banana, milk, peanut butter, honey, ice", method: "Blend everything until smooth and serve cold." },
  { name: "Chicken soup", cuisine: "Western", diet: "non_vegetarian", meals: ["lunch", "dinner", "detox"], serving: "1 bowl (250 ml)", kcal: 130, protein: 12, carbs: 10, fat: 4, ingredients: "Chicken, carrot, celery, onion, garlic, herbs", method: "Simmer chicken with vegetables and herbs until tender, then shred the meat back into the broth." },
  { name: "Oats porridge with milk", cuisine: "Basics", diet: "vegetarian", meals: ["breakfast", "detox"], serving: "1 bowl (40 g oats)", kcal: 300, protein: 12, carbs: 42, fat: 9, ingredients: "Rolled oats, milk, honey, fruit", method: "Simmer oats in milk for 5 minutes, stirring, then top with fruit." },
  { name: "Boiled egg", cuisine: "Basics", diet: "eggetarian", meals: ["breakfast", "snack"], serving: "1 large", kcal: 75, protein: 6, carbs: 1, fat: 5, ingredients: "", method: "" },
  { name: "Banana", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "1 medium", kcal: 105, protein: 1, carbs: 27, fat: 0, ingredients: "", method: "" },
  { name: "Apple", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "1 medium", kcal: 95, protein: 0, carbs: 25, fat: 0, ingredients: "", method: "" },
  { name: "Papaya", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "1 cup (150 g)", kcal: 60, protein: 1, carbs: 15, fat: 0, ingredients: "", method: "" },
  { name: "Almonds", cuisine: "Basics", diet: "vegan", meals: ["snack"], serving: "10 nuts (12 g)", kcal: 70, protein: 3, carbs: 3, fat: 6, ingredients: "", method: "" },
  { name: "Peanuts", cuisine: "Basics", diet: "vegan", meals: ["snack"], serving: "30 g", kcal: 170, protein: 8, carbs: 5, fat: 14, ingredients: "", method: "" },
  { name: "Roasted chana", cuisine: "Basics", diet: "vegan", meals: ["snack"], serving: "30 g", kcal: 110, protein: 6, carbs: 18, fat: 2, ingredients: "", method: "" },
  { name: "Whole milk", cuisine: "Basics", diet: "vegetarian", meals: ["breakfast", "snack"], serving: "1 glass (250 ml)", kcal: 150, protein: 8, carbs: 12, fat: 8, ingredients: "", method: "" },
  { name: "Boiled sweet potato", cuisine: "Basics", diet: "vegan", meals: ["snack", "detox"], serving: "150 g", kcal: 130, protein: 2, carbs: 30, fat: 0, ingredients: "", method: "" },
  { name: "Ghee", cuisine: "Basics", diet: "vegetarian", meals: ["detox"], serving: "1 tsp (5 g)", kcal: 45, protein: 0, carbs: 0, fat: 5, ingredients: "", method: "" },
];

function sqlString(value: string): string {
  return "'" + value.replace(/'/g, "''") + "'";
}

function sqlArray(values: string[]): string {
  return "array[" + values.map(sqlString).join(", ") + "]::text[]";
}

function toRow(d: Dish): string {
  return `(${sqlString(d.name)}, ${sqlString(d.cuisine)}, ${sqlString(d.diet)}, ${sqlArray(d.meals)}, ${sqlString(d.serving)}, ${d.kcal}, ${d.protein}, ${d.carbs}, ${d.fat}, ${sqlString(d.ingredients)}, ${sqlString(d.method)})`;
}

const sql = `-- Seed data for the global \`foods\` library, batch 1: the original
-- prototype dishes (docs/build-brief.md section 5), reclassified with a
-- diet tier and meal category. Generated by scripts/seed-foods.ts --
-- do not hand-edit; change the script and regenerate instead.

insert into public.foods (name, cuisine, diet, meal_category, serving, kcal, protein_g, carbs_g, fat_g, ingredients, method)
values
${BATCH_1.map(toRow).join(",\n")};
`;

const outPath = join(process.cwd(), "supabase", "migrations", "20260922050000_seed_foods_batch_1.sql");
writeFileSync(outPath, sql, "utf8");
console.log(`Wrote ${BATCH_1.length} dishes to ${outPath}`);
